### ISSUE TITLE
Real Time Packets: Data failed to load, please reload the page and try again

### ISSUE THREAD

**Issue by IFoundABugAgain** [helium/console#1005]
1. Are you using Helium hosted Console or running your own open source Console?
Running own open source console.
2. If you are on Helium hosted Console, which url are you currently on? 
helium.futuredecisions.net
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Organisation: Future Decisions DeviceID: d0298989-7eb1-4fa2-b2f0-bc628fe3561f

Please describe your issue:
"Real Time Packets
Data failed to load, please reload the page and try again "

This does not seem to work any more. Am on the latest build as of time of writing.
![image](https://user-images.githubusercontent.com/57115812/151639624-7ee64e0c-c4e2-485f-a57d-57ede2bac5a5.png)

![RealTimePackets](https://user-images.githubusercontent.com/57115812/151639544-49a1f1b5-41fe-463b-ad14-fd2df4700dfa.png)

**Comment by vicmgs** [comment]
Try looking at your helium/console container logs and capturing the error it shows when you visit the breaking device page. 

Also, try creating a new device and seeing if "Data failed to load..." still shows in the event log.

**Comment by vicmgs** [comment]
closing for now
