### ISSUE TITLE
Feature request - expand box "ADVANCED - JSON MESSAGE TEMPLATE (OPTIONAL)" if changed from default

### ISSUE THREAD

**Issue by slavendam** [helium/console#1014]
Feature request - expand "ADVANCED - JSON MESSAGE TEMPLATE (OPTIONAL)" if used.

If user changed something in Integrations ADVANCED - JSON MESSAGE TEMPLATE (OPTIONAL), when he comes back to Integration expand this area automaticaly. If it is default, leave it collapsed.
This is useful for UX because it is already on the bottom, out of sight, and it is important to see it if user edited it when he created Integration.

**Comment by vicmgs** [comment]
see next release
