### ISSUE TITLE
open source console and containerization (docker)

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1018]
Received feedback from open source users looking to commercialize offering:

To limit downtime during upgrades, provide a way to use a container (docker) for Console latest build similar to the experience provided by open source router.

**Comment by vicmgs** [comment]
a problem with containerizing console is if the db migrations dont run properly for whatever reason, users cannot change migrations code to fix

**Comment by vicmgs** [comment]
released in https://github.com/helium/console/releases/tag/2022.02.10
