### ISSUE TITLE
Integration Issue didn't cause an alert

### ISSUE THREAD

**Issue by charlesfayal** [helium/console#1027]
1. Are you using Helium hosted Console or running your own open-source Console?
Helium hosted

2. If you are on Helium hosted Console, which url are you currently on? 
console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
fdd37e62-094c-40c0-9a48-e29db628785a

Please describe your issue:

An integration occurred, and we didn't get alerted even though we have alerts setup.

**Comment by vicmgs** [comment]
please provide more details

What happened with the integration, which integration name is it, which alert name did you set up, when did it happen
