### ISSUE TITLE
Add specific console API to allow activation/desactivation of a device

### ISSUE THREAD

**Issue by laurentchivot** [helium/console#1029]
After provisioning of a device, it would be very useful to be able to activate/deactivate a device from an API call.

1. based on an UUID
2. based on a Label
and more generally based on common parameters used for the API

Ex: name, Application EUI, Application Key, and Device EUI

Like it is possible to do so for a Label (Add/remove)
> Add Device Label 
POST  https://console.helium.com/api/v1/devices/:device_id/labels
Add Device to Label

It could be something like :

POST  https://console.helium.com/api/v1/devices/:device_id/state

Thank you

**Comment by vicmgs** [comment]
@laurentchivot 
We can add 1 for sure.

What do you mean by "based on a Label"? All devices under that label will be marked active/inactive?

Also, for "based on common parameters used for the API", should all devices found under those attributes be marked active/inactive?

**Comment by laurentchivot** [comment]
Hello,
@vicmgs Thank you for evaluating my request.

> All devices under that label will be marked active/inactive? >> YES

> based on common parameters used for the API", should all devices found under those attributes be marked active/inactive? >> YES

based on UUID is the MVP ;-), Label is Priority 1 and others are cherry on the cake , depends on the backlog.

Regards

Laurent
