### ISSUE TITLE
Data credits used multiple times for the same packet

### ISSUE THREAD

**Issue by yanxke** [helium/console#1042]
1. Are you using Helium hosted Console or running your own open source Console?

Hosted

2. If you are on Helium hosted Console, which url are you currently on? 

https://console.helium.com/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Ke Inventions, 99164dad-d554-4ee9-8791-d6cd5c06e74d

Please describe your issue:

When the same packet is received from multiple hotspots, it is counted against multiple data credits used.  Instead, it should be one credit used.  I can only control the number of packets I send, but I can't control the number of hotspots out there receiving it.  It doesn't seem like a fair way to account for this.

**Comment by jdgemm** [comment]
hi, yes you can control the number of packets received using the multiple packet feature: https://docs.helium.com/use-the-network/console/multi-packets/

However, as written in the documentation:
Regardless of the Multiple Packet feature setting, under certain conditions the system purchases multiple packets to help ensure successful packet transmission (these cost additional Data Credits and happen automatically). These include: initial joining of the device (up to five packets) and downlinks that contain data payloads (up to three packets). These additional packets help ensure connection reliability to downlink via the Hotspot with the strongest connection.
