### ISSUE TITLE
Provide ability on mobile UI to scan device qr codes to add keys

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1044]
Entering device keys (deveui, appeui) requires manual input. This is cumbersome, and rife for errors. 

Based on mobile survey data a popular request was the ability to scan device qr codes to populate key information.

update: only support lora official qr code standard: (https://www.google.com/url?q=https://lora-alliance.org/wp-content/uploads/2020/11/TR005_LoRaWAN_Device_Identification_QR_Codes.pdf&sa=D&source=calendar&ust=1645558316158820&usg=AOvVaw00nsWxqgH2dTC5cvNxTvsL)

**Comment by vicmgs** [comment]
so this should be mobile only feature, and I would need some test QR codes

**Comment by jdgemm** [comment]
> so this should be mobile only feature, and I would need some test QR codes

yes, and will provide, thanks

**Comment by jdgemm** [comment]
Spec and examples here: https://lora-alliance.org/wp-content/uploads/2020/11/TR005_LoRaWAN_Device_Identification_QR_Codes.pdf

**Comment by vicmgs** [comment]
will go into staging
