### ISSUE TITLE
API Feature request: Add option for adding functions and integrations through POST API function

### ISSUE THREAD

**Issue by slavendam** [helium/console#1050]
It would be really useful if there is option to add functions and integration with POST API call. 

User can send function code as string in body, together with name and other parametrs.

Also for integration user can send URL and provide headers in body.

These options can be integrated with QR codes later which is as I can see on roadmap also.

**Comment by alexnanzer** [comment]
Could be partly integrated by this? #1028

**Comment by vicmgs** [comment]
functions not yet, integrations partly for now

**Comment by jdgemm** [comment]
What type of functions are you looking to add? If it's a not a prebuilt function (i.e., custom) how do you foresee adding multiple lines of javascript code in a API call? Also how would you validate to ensure the output was correct?

**Comment by slavendam** [comment]
This is response body in Console for function:

>     "data": {
>         "function": {
>             "__typename": "Function",
>             "active": true,
>             "body": "function Decoder(bytes, port) { \n  // Decode an uplink message from a buffer (array) of bytes to an object of fields. \n  //Decoder for GLAMOS Walker device. \n  \n  var decoded = {}; \n  \n  decoded.latitude = ((bytes[0]<<16)>>>0) + ((bytes[1]<<8)>>>0) + bytes[2]; \n  decoded.latitude  = (decoded.latitude / 16777215.0 * 180) - 90; \n  decoded.latitude = +decoded.latitude .toFixed(7); \n  \n  decoded.longitude = ((bytes[3]<<16)>>>0) + ((bytes[4]<<8)>>>0) + bytes[5]; \n  decoded.longitude = (decoded.longitude / 16777215.0 * 360) - 180;\n  decoded.longitude = +decoded.longitude .toFixed(7); \n  \n  var altValue = ((bytes[6]<<8)>>>0) + bytes[7]; \n  var sign = bytes[6] & (1 << 7); \n  if(sign) \n  { \n    decoded.altitude = 0xFFFF0000 | altValue; \n  } \n  else \n  { \n    decoded.altitude = altValue; \n  } \n  \n  decoded.ant  = bytes[8]; \n  \n  decoded.accuracy = 3; \n  \n  decoded.position_num = bytes[9]; \n  \n  \n  return decoded; \n}",
>             "format": "custom",
>             "id": "  ",
>             "name": "Glamos decoder",
>             "type": "decoder",
>             "updated_at": "2022-02-26T13:30:09"
>         }
>     }

As I can see, function JS code is saved as a string. So user can send object in POST call which will include "body", "format" and "name" fields. All these fields will be strings.

This API is probably for more advanced users who already have validated functions or they will be able to validate through UI of Console.
This is really useful for people who are integrating large number of devices and they already have list of different functions that are already validated.

**Comment by jdgemm** [comment]
The problem is the number of fields is not consistent across devices.

Also, if a user has already validated the function through Console UI, what would they be using the API for?

**Comment by slavendam** [comment]
As I said, it is probably for advanced users because API uses this kind of users.

For me personally it is really useful to help our customers to easily and fastly setup Helium Console. User will be able with just 1 click add device, add function, add integration, and connect them in flow.
For regular users, even using UI Console is complicated, understanding keys, integrations, decoders... They want just one click setup to start using it fast.

Device producers can provide QR code which will add device to Console and maybe also add Function for that specific device.

**Comment by jdgemm** [comment]
Would adding a function once it has already been defined and validated via the Console be useful? Creating a function via API by sending javascript code is not recommended at this time.

**Comment by jdgemm** [comment]
There is a decoder repo managed by the community here: https://github.com/helium/console-decoders

Approved functions will be considered based on usage demand.
