### ISSUE TITLE
API - Activate/Deactivate Device

### ISSUE THREAD

**Issue by Famosi** [helium/console#1052]
Reading the documentation for the console api, it doesn't look like you can turn a device on or off. 

This feature would be useful to allow a minimal DC consumption in case you don't need to receive data from the device.

Anyway, I'm looking for a solution to make (remotely using the api) the device send packets only when a request to receive data has been made. Can you tell me how to do this? Any advice is welcome!

**Comment by vicmgs** [comment]
duped by https://github.com/helium/console/issues/1029 

releasing next week

**Comment by ambuznego** [comment]
This is already going to be in our release next week 👍

**Comment by Famosi** [comment]
Is it possible to get the current device status?
