### ISSUE TITLE
Staging API - Get Device Status (active/inactive)

### ISSUE THREAD

**Issue by Famosi** [helium/console#1055]
With the new staging API it is possible to activate/deactivate a device. 
However, I can't find a way to get the current device status. 

Am I missing something?

**Comment by vicmgs** [comment]
https://docs.helium.com/api/console/#device-by-uuid

under active key

**Comment by Famosi** [comment]
Sorry but what's the attribute that states if the device is active or not?

**Comment by vicmgs** [comment]
The doc might not be up to date. Try hitting the actual endpoint

**Comment by Famosi** [comment]
This is the result I have:
```

{
        "adr_allowed": null,
        "app_eui": "....",
        "app_key": "...",
        "cf_list_enabled": null,
        "config_profile_id": null,
        "dc_usage": 6459,
        "dev_eui": "...",
        "id": "...",
        "in_xor_filter": true,
        "labels": [
            {
                "adr_allowed": null,
                "cf_list_enabled": null,
                "config_profile_id": null,
                "id": ".....",
                "name": "gps",
                "rx_delay": null
            }
        ],
        "last_connected": "2022-02-18T08:12:49",
        "name": "Prova",
        "organization_id": ".....",
        "oui": 1,
        "rx_delay": 1,
        "total_packets": 6459
    }
```

**Comment by vicmgs** [comment]
on staging API

[
    {
        "active": true,
        "adr_allowed": null,
        "app_eui": "",
        "app_key": "",
        "cf_list_enabled": null,
        "config_profile_id": null,
        "dc_usage": 4680,
        "dev_eui": "",
        "id": "",
        "in_xor_filter": true,
        "labels": [],
        "last_connected": "2022-01-12T01:55:11",
        "name": "testttt",
        "organization_id": "",
        "oui": 4,
        "rx_delay": 1,
        "total_packets": 4680
    }
]
