### ISSUE TITLE
Azure iot-hub feature request

### ISSUE THREAD

**Issue by michaeldjeffrey** [helium/console#1061]
**Currently:**
For Azure iot-hub integration we require User's to input:
- Hub Name
- Policy Name
- Primary Key

Hub Name can be confusing one because it's only part of the full URL that's visited for managing iot-hub.
Primary Key is also open for being misconfigured: not copying enough, or copying invisible characters.

**Request:**
Provide a field where a users can provide a connection string from iot-hub and the interface will can pull out the useful pieces.

**Comment by ambuznego** [comment]
@jdgemm we will need docs updated for this.
