### ISSUE TITLE
Console organization feature requests

### ISSUE THREAD

**Issue by wprojects** [helium/console#1072]
I have been using Helium console and have enjoyed how simple it is to use. I am currently a developer for my company that builds the Helium network, and we are sponsoring data credits for a lot of people to help our city grow in IOT. That being said, I have been looking around console and noticed a few things that would really help out for business or groups that are being a parent organization for a lot of different organizations. So here is what I have come up with:

1. Labels: I think it would be super helpful if we could label or group our organizations in the console. If I had for example 40 organizations I am parenting and funding data credits to, it will become increasingly difficult to distinguish whether or not that organization is part of our student group, our developers program, or part of our teams organization. Labels would allow me to separate groups of organizations so I know who and what I'm dealing with and can keep it a little bit more clean from a management perspective. That being said, this feature would also tie into my second feature request.

2. Automatic DC Renewals: If I am a parent organization that has created an umbrella of organizations that I fund and manage, it would be extremely nice to be able to set an automatic transfer of data credits, sort of like what you guys already have available but instead of purchasing the credits automatically, I'd like to be able to transfer credits to an organization automatically when that organization has reached a certain threshold. To refer to my first feature request, it would be really nice if we could set for example a 10,000 dc transfer for any organization in that label that drops below 1k data credits. If I could set the renewal rates based on label or individual organizations that would be great because there might be some groups I create that I want to fund all the same and you could do that easily with the label system, or I could individually set a renewal loop on a specific on too

3. DC Transfer Statistics: Last of all, I think that it would be extremely beneficial to have an Organization DC Transfer page that show's different stats such as how many data credits total have been purchased, and how many have been transferred such as (weekly, monthly, year, or all time). This would be very beneficial to any company or group that is managing a bunch of organizations and funding their credits to be able to monitor their dc usage and how much is going where. If you could see individually how much you have sent each organization as well that would be great. Being able to export this data to JSON would be extremely useful for companies to be able to monitor their funding and spending over console.

Any suggestions or comments would be great! Thanks

**Comment by HiGregory** [comment]
Hi @wprojects great feedback.

We've built a lot of this in our partnership with Helium for IoT Asset Monitoring at the organizational level
at Helium on DataGovs. [See DataGovs <> Helium News](https://blog.helium.com/own-your-city-data-with-datagovs-starting-in-miami-c4623ef8e9c)

- We have labels that can sit for IoT Devices and Hotspots
- We have organization roles and subcategories focused on data governance at the access level
- It's not available in our Dashboard now, but our Mobile app on iOS is exploring this piece to track DC usage.


If you and your team are open to working with a provider who built a solution on top of Helium let me know.

Email is team@datagovs.com

**Comment by jdgemm** [comment]
hi @wprojects thanks for using the network:

label information here: 
https://docs.helium.com/use-the-network/console/labels/

Data credit automatic renewal is available, currently, the setting is fixed at 500,000 DC, what other increments are you thinking?

Data Credit transfer stats: these are shown on the Data Credits page, which includes both purchases and transfers. Transfer stats are shown both on the transfer from and to Organizations.

**Comment by jdgemm** [comment]
@wprojects I'm closing this, but if there's additional suggestions/feedback feel free to open new issues.
