### ISSUE TITLE
Device limit issue

### ISSUE THREAD

**Issue by RARomano** [helium/console#1082]
I'm importing some devices to Helium using the Console (VIP) API. 

Everything worked until I reached the 10000 devices. After that, I started to get `500` responses back, without any description. 
Looking at the documentation, I could not find anything about a hard limit and so I started to look at the console's codebase.

https://github.com/helium/console/blob/cd07f70d493d671b2364ac8fa4c54b83db9e4184/lib/console/devices/devices.ex#L118

Is there a reason for that limit? 
There's nothing that prevents me to change my organisation name to `Discovery Mode (Helium)` and create more devices.

![image](https://user-images.githubusercontent.com/12012898/159721896-b4997a87-ecde-4e29-964e-ae13bf04314a.png)

Can this become an organisation setting instead?

**Comment by jdgemm** [comment]
Thanks, and appreciate your usage on the network. We've completed frontend scaling work which makes us confident to update this limit to 100,000. In addition, this will be a configuration that open source users can change.

**Comment by vicmgs** [comment]
deployed onto console-vip.helium.com

**Comment by RARomano** [comment]
Thank you very much!
