### ISSUE TITLE
Interest to build a new pre-built integration

### ISSUE THREAD

**Issue by pebneter** [helium/console#1091]
I'm a co-founder of Apilio, which is offering a consumer service for home automation, and we are interested to build an integration with Helium to forward sensor data to Apilio.
I already managed to forward data to Apilio with the generic tools available (HTTP Integration on Helium + REST API on Apilio), but it would be much more convenient for less tech-savvy users if there was an easier way.

For now I'm interested to get a documentation with details about the technical options of the interface. I hope there is a way that is easy to implement from our side

Philipp

**Comment by jdgemm** [comment]
hi Philipp, thanks for the request. The team's building a Community Marketplace which will allow users from the community to contribute integrations and Console hosters to enable whichever Console elements they want to for their users. Please follow along progress here: https://github.com/helium/console/issues/1131. We look forward to your future contribution.

**Comment by pebneter** [comment]
ok, thanks!
If I understood correctly, that won't work for the console that is hosted by Helium itself (https://console.helium.com)?
