### ISSUE TITLE
Primary key is missing in IoT Hub integration

### ISSUE THREAD

**Issue by matsujirushi** [helium/console#1108]
1. Are you using Helium hosted Console or running your own open source Console?  
Helium hosted Console

3. If you are on Helium hosted Console, which url are you currently on?  
https://console.helium.com/integrations/new

4. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).  
Organization name is SeeedJP

Please describe your issue:

When the Primary Key is cut from the Primary Key Connection String, the final "=" is missing.

![image](https://user-images.githubusercontent.com/8079404/162549434-356b1492-e277-43b0-95ca-9fa68799bfb3.png)

**Comment by vicmgs** [comment]
Thank you for reporting, we will get it fixed by the next release.

In the meantime as a workaround, you can add the equal sign by updating the primary key after creating the integration.
