### ISSUE TITLE
Multiple packets changed from ALL to 10 automaticaly

### ISSUE THREAD

**Issue by slavendam** [helium/console#1112]
We got 10 users today who are reporting issue with automatic change of Multiple packets in production Console. Number of packets is changed from "ALL packets" to "10 packets".

**Comment by ambuznego** [comment]
Hi @slavendam, thank you for reporting this. We recently updated the limit on multibuy (see https://github.com/helium/console/pull/1094). 10 was originally the value that represented all packets, so for existing records, this needed to be bumped up to 21 (per the code change). This has now been done and should the issue.
