### ISSUE TITLE
Cert issue on staging console.

### ISSUE THREAD

**Issue by jthiller** [helium/console#1129]
1. Are you using Helium hosted Console or running your own open source Console?

Hosted

2. If you are on Helium hosted Console, which url are you currently on? 

https://staging-console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:
![image](https://user-images.githubusercontent.com/1965053/163661640-d4e4a2ae-b057-46b0-94b9-3f477af97d20.png)

**Comment by jdgemm** [comment]
@jthiller the url  you should be using is: https://staging-console.helium.wtf/
