### ISSUE TITLE
Community Marketplace MVP

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1131]
Community Marketplace provides a way for Helium community members to contribute and share Console elements. Initially, Console elements include Integrations, and Decoders, but over time the community could provide others.

User flow steps

Step 1. The community contributes and shares Console elements (phase 1 Integrations) to the Console open-source github repository.

Step 2. Shared Console elements are reviewed by the Helium Foundation technical team. 

Step 3. Approved Console elements are available for open source hosters to access with new releases.

Step 4. Console hosters enable/disable Console elements on their instance of Console to make them available on the Console UI for their end-users. Default is all the Console elements.

Step 5. In Console, users choose elements to use.

Community Marketplace participants:
- Community members: contribute Console elements to Community Marketplace.
- Helium Foundation technical team: approves Console elements.
- Console hosters: choose which approved Console elements are exposed to Console users on Console UI.
- Console users: choose which Console elements to enable and use.

**Comment by vicmgs** [comment]
-[ ] Backend Changes, new community integration types
-[ ] UI Changes, integration intro pages

**Comment by vicmgs** [comment]
- [ ] backend changes
- [ ] UI changes

**Comment by vicmgs** [comment]
no community screenshots for now

**Comment by pebneter** [comment]
Since this has been closed: is the community marketplace now ready?

**Comment by vicmgs** [comment]
estimated release is this upcoming Thursday
