### ISSUE TITLE
Add region to downlink

### ISSUE THREAD

**Issue by macpie** [helium/console#1140]
See https://github.com/helium/router/issues/651 for ref

Sometimes user wants to send a downlink before joins happen. At this point, router does not know which region it is, so the downlink is dropped. In the UI, include a dropdown box of optional selections (default is device default region) and list of options of regions we support.

**Comment by mikev** [comment]
Helium document our supported plans here - https://docs.helium.com/lorawan-on-helium/frequency-plans/

Currently 4 plans are documented:
US915
AU915
EU868
CN470

It is undocumented, but I believe we do support the 4 variants of AS923 (This plan applies to most countries in Asia, Oceania and some countries in South and Central America)
AS923_1
AS923_2
AS923_3
AS923_4
