### ISSUE TITLE
Stripe receipts for recurring payments are not sent automatically

### ISSUE THREAD

**Issue by ambuznego** [helium/console#1146]
Users have auto renewal set up but don't receive the stripe receipt and usually have to contact us to request one.

~~On the router device_controller, we use "Recurring Charge" as user_id since we don't have a current_user to access at this point: https://github.com/helium/console/blob/master/lib/console_web/controllers/router/device_controller.ex#L551~~

**UPDATE:** The `receipt_email` attribute is missing. 

So stripe does not have an email to send the receipt to.

Must figure out how to grab the appropriate user object to pass on the id that should match to a stripe user id.

**Comment by vicmgs** [comment]
The recurring charge attribute probably isn't what's causing the issue.

I think it's the "receipt_email" attribute when we submit payments to stripe.com/v1/payment_intents, but yes somehow we need to populate the "receipt_email"

**Comment by ambuznego** [comment]
> The recurring charge attribute probably isn't what's causing the issue.
> 
> I think it's the "receipt_email" attribute when we submit payments to stripe.com/v1/payment_intents, but yes somehow we need to populate the "receipt_email"

that makes more sense and the fix is easier that way 👍 thanks

**Comment by vicmgs** [comment]
we can probably search for the most recent dc_purchase that isn't "Recurring Charge", and search for that user_id in the memberships table, which should result in an email. In the edge cases that those users have been deleted from the org, then we leave it blank I guess.

Alternatively, we could just ask users to specify a recurring charge email to always send to. New column to be added in orgs table next to the automatic_charge_amount & automatic_payment_method columns.
