### ISSUE TITLE
could not figure out how to get this working 

### ISSUE THREAD

**Issue by rickpromod** [helium/console#1152]
1. Are you using Helium hosted Console or running your own open source Console?

2. If you are on Helium hosted Console, which url are you currently on? 

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue: I don't know what I'm doing and I can't figure out what to do

**Comment by rickpromod** [comment]
Tangy Frost Ladybug  addres is 54 Winding Valley Drive Rockmart Georgia 30153 it's a Sensecap m1

**Comment by vicmgs** [comment]
Hi, you need to download the Helium App from your device app store and follow the instructions there. This repository is not at all related to your hotspot.
