### ISSUE TITLE
Feature Request: Tenant Management

### ISSUE THREAD

**Issue by kevinelliott** [helium/console#1153]
1. Are you using Helium hosted Console or running your own open source Console?

Running own open source Console.

2. If you are on Helium hosted Console, which url are you currently on? 

N/A

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Add tenant management. (I asked on Discord but did not hear back. Is this planned already?)

It would be great to be able to manage tenants in the UI (as a superuser of Console). As users create accounts and leverage the Console, there becomes a need to see a high level overview of who has teams, accounts, etc. And there is some need to understand overall usage and billing needs. For example, if I am paying for DC on behalf of users in the org, or in other orgs, how will I know if I need to refill?

Additionally, it would be practical for growing a hosting service which allows management, monitoring, and support in a meaningful way.

I am happy to contribute (but not entirely own) to the implementation for this effort.

**Comment by jdgemm** [comment]
Currently, there is no plan to build what you're asking and at this time there are higher priorities. In the meantime, this information can be manually queried from the db.

**Comment by kevinelliott** [comment]
Understood. Are you taking pull requests from non Nova?
