### ISSUE TITLE
Wording tweaks for sprint 76

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1159]
Preferred Hotspot:

Hotspots marked as Preferred will be chosen to deliver packets before others.

>

Only Hotspots marked as Preferred will be chosen to attempt packet delivery.

Year footer:

© 2021 Helium Systems

> 

© 2022 Helium Systems

**Comment by ambuznego** [comment]
@jdgemm can you clarify where the preferred hotspot lines should go?

**Comment by ambuznego** [comment]
@jdgemm confirming it's this part: 
<img width="879" alt="image" src="https://user-images.githubusercontent.com/51131939/168914411-c2cf1567-1760-4d2f-ad5d-dc05842ef561.png">

**Comment by ambuznego** [comment]
also a question: https://github.com/helium/console/pull/1160#discussion_r875284824

Should it say Nova? @jdgemm

**Comment by jdgemm** [comment]
Keep status quo
