### ISSUE TITLE
Helium Console: Foundation clarity on login

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1171]
Provide more clarity for users of Helium Console: Foundation. Add following text to initial login screen:

Helium Console: Foundation

Submit your email address to receive a login link and learn about the network (10 device limit). For larger deployments check providers here: https://docs.helium.com/use-the-network/console/hosting-providers/

<img width="424" alt="Screen Shot 2022-05-25 at 9 35 59 AM" src="https://user-images.githubusercontent.com/36315460/170315772-44961778-9edb-4ae5-9f4c-e622081ab42e.png">

**Comment by vicmgs** [comment]
in staging today
