### ISSUE TITLE
Console login redirect into a death spiral

### ISSUE THREAD

**Issue by BFGNeil** [helium/console#1176]
Hi,

Im currently doing a lot of work in console so generally I leave console open as a tab.

When I come back to it in a day after closing my laptop, I keep getting stuck in this redirect loop that ends with me getting a 423 too many requests message, if I try another browser/fresh cache it just spins the loading icon.

Was locked out for about 2 hours today.

**Comment by vicmgs** [comment]
@BFGNeil
1. How long are you are leaving console before coming back to it?
2. What is the Chrome developer console saying when you get these 423 errors?
3. Do you have copies of these 423 error logs?
4. Which organization are you generally looking at?

**Comment by vicmgs** [comment]
closing for now, feel free to re-open
