### ISSUE TITLE
Can´t find or add any hotspot in "Coverage"

### ISSUE THREAD

**Issue by kairetzlaff** [helium/console#1195]
1. Are you using Helium hosted Console or running your own open source Console? 
Hosted

3. If you are on Helium hosted Console, which url are you currently on? 
https://console.helium.com/coverage

5. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Nevergiveup Org, 8eb9b15b-1adf-41ae-b23f-eb673c6b9e83

Please describe your issue: I can´t resolve or find any Helium HS in Coverage. I need pinning a device to a Hotspot.

**Comment by vicmgs** [comment]
Which coverage page are you unable to find a hotspot? Does searching for a hotspot name not work for you?

**Comment by vicmgs** [comment]
Closing as we have a fix that should help, reopen issue if needed.
