### ISSUE TITLE
Unfollowing a hotspot prompts misleading message regarding preferred hotspots

### ISSUE THREAD

**Issue by ardevd** [helium/console#1210]
1. Are you using Helium hosted Console or running your own open source Console?
Helium Console

2. If you are on Helium hosted Console, which url are you currently on? 
console.helium.com/

Please describe your issue:

When marking a hotspot as followed (blue flag) and subsequently, unfollowing it by checking the checkbox and selecting "unfollow" from the dropdown box, a dialog pop ups with the following text:

> Are you sure you want to Unfollow this Preferred Hotspot?
If you continue, the Preferred Hotspot setting will be turned off in all existing Packet Configurations, since there must be at least one Preferred Hotspot for this feature to be enabled.

The message indicates that the hotspot was actually marked as "preferred" but in reality it was only followed and is generally just confusing

**Comment by ambuznego** [comment]
@ardevd Thanks for reporting! We'll get a fix into the next release.
