### ISSUE TITLE
favicon missing on opensource console

### ISSUE THREAD

**Issue by disk91** [helium/console#1211]
Since the version allowing custom design for the console, the favicon has been removed (see https://console.helium-iot.eu )
I would like to have it back as much as possible ;)

It would also be nice to have on the console REAME.md file the link to the documentation to customize the console design and the way to do it with container version.

**Comment by vicmgs** [comment]
Will be fixed for next release. In the meantime, use in your .env:

APP_TITLE=Helium Console
APP_FAVICON_URL=https://console.helium.com/favicon.png

**Comment by disk91** [comment]
thank you
