### ISSUE TITLE
bug while changing device labels over the api 

### ISSUE THREAD

**Issue by nosmaster89** [helium/console#1241]
1. Are you using Helium hosted Console or running your own open source Console?
helium
2. If you are on Helium hosted Console, which url are you currently on? 
console.helium
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
terrahash 

8a27326c-b214-42c9-9f25-ba9e9ca2b4de

Please describe your issue
while trying to change labels via the api , its causing my integrations to break 
![image](https://user-images.githubusercontent.com/87389996/185485797-0e7e1747-d03b-4c2a-9f3c-3f57254e6730.png)

![image](https://user-images.githubusercontent.com/87389996/185485899-a7832ad7-7f68-4102-8b9d-3c8fb2a39aa7.png)

if i drag the device to a integration manually and then remove the edge , the label continues to work until i call the api to adjust the labels

**Comment by vicmgs** [comment]
fixed deployed to foundation
