### ISSUE TITLE
Hotpots not showing up in 

### ISSUE THREAD

**Issue by ccall48** [helium/console#1255]
1. Are you using Helium hosted Console or running your own open source Console?
- Using helium console.

3. If you are on Helium hosted Console, which url are you currently on?
- console.helium.com

5. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

- Callcott Refrigeration
- mapper device: 0c0d38d2-3a66-43cb-877a-10a836f9cc3c
- Issue not device related seems more hotspot related

Please describe your issue:

I have two hotspots which were added to the network at the end of november, both of which have relayed packets by myself and others in the area. 

my problem is however i cannot find these by hotsport name or wallet address to add them to my coverage hotspots. 

the hotspots show up on all the helium mappers i am pushing the data too though, but in my console i just seem to get 2 x unknown hotspots which should be mine but i cant add them etc. Have attached an image of i see atm below.
also asked on discord, if you're on there here is some msg links:
- https://discord.com/channels/404106811252408320/730245319882965093/1047652615682527292
- https://discord.com/channels/404106811252408320/730245319882965093/1048412182284615711

![Screenshot 2022-12-05 at 08 11 54](https://user-images.githubusercontent.com/34887996/205516176-fe9ea723-86e3-4e6a-a940-7a38c7906ed3.jpg)

**Comment by ambuznego** [comment]
Thank you for reporting this. We are looking into this.

**Comment by ambuznego** [comment]
@ccall48 This should now be resolved. The job syncing the database with new hotspots had stopped running. We have a fix in place now. Thanks again for reporting.
