### ISSUE TITLE
The Helium Non-VIP Dev Console stopped processing or displaying sensor data packets as at 5.41am AEST.

### ISSUE THREAD

**Issue by plainsimpleIoT** [helium/console#1270]
**Issue Ticket**

**Description:** It has been observed that the Helium Non-VIP Dev Console ceased processing or displaying sensor data packets starting from 5.41am AEST. Prior to this, network issues were reported between 2.26am AEST and 10:01am AEST, during which rectifications were implemented to Packet Routers. Although a tracker sensor (Digital Matter Yabby) recorded information in the Cargo Application at 4:26pm AEST and 4:44pm AEST, these sensor packet transfers are not reflected in the Console.

**Potential Consequences and Impact:**

1. **Unknown data credit usage:** The current issue makes it difficult to determine the data credit usage accurately, which can affect the billing and cost management for Community Sensor operators.
2. I**mpacted data traffic rewards:** Without a reliable source of sensor data packet transfers currently provided through the Console, Community Sensor operators will not be able to reconcile the consumption of data credits to data traffic rewards. This discrepancy can lead to inconsistencies in the calculation of rewards, potentially impacting the incentives and benefits received by the operators.
3. **Operational challenges:** Community Sensor operators rely on the Console for efficient management and maintenance of their sensor fleet. With the Console not processing sensor data packets, operators may face difficulties in effectively managing their sensors.

**Expected Outcomes Sought:**

**Prompt action:** The Community Sensor Operator seeks prompt action to address the issue, as the lack of Console functionality hinders their operations.
**Clarification on manual sensor resets:** The Operator needs to understand whether they have to manually reset all existing sensors in order to have Console operations recommence. This outcome is considered suboptimal and should be avoided if possible.
**Non-intrusive rectifications:** The Operator hopes that the Console provider can perform non-intrusive rectifications that do not require any manual interventions from the Operator. This would ensure a smoother and more efficient resolution of the issue.
Steps to Reproduce (if applicable): Not applicable

**Priority: High**

**Affected Components:**

Helium Non-VIP Dev Console
Packet Routers (potential)

**Attachments (if any):**

**Screenshot from the Console:** Last recorded time that the Console reported data packet transfer.
**Screenshot from the Cargo Application:** Sensor information updates 2 minutes and 20 minutes ago from 4:44pm AEST.

**Additional Notes:** Please investigate the issue promptly and provide a resolution to ensure the proper functioning of the Helium Non-VIP Dev Console, accurate tracking of data transactions, and synchronization with the Cargo Application. The Community Sensor Operator seeks clarity on whether manual sensor resets are necessary and hopes that non-intrusive rectifications can be performed by the Console provider, minimizing the need for Operator interactions.

**Console Organizational ID: f10e9efb-4ecc-4952-90c6-352ff4a63fa3**
![1TrackerParsingDatatoCargo-squashed](https://github.com/helium/console/assets/133552851/08d1dceb-a223-4721-a6d2-6f72dd981d93)
![2TrackerCargoApp-squashed](https://github.com/helium/console/assets/133552851/2d1e3063-f5ab-476a-937d-40c793c60f1a)

**Comment by plainsimpleIoT** [comment]
Addendum#1: Picture showing that the packets relayed from devices in the Organisation timestamped approx 7:14pm AEST stopped and have not restarted.
![ConsoleDevicePacketsRelayed7_15pmAEST-squashed](https://github.com/helium/console/assets/133552851/a89fbe75-29da-496c-ab23-eaebd29e076b)

**Comment by plainsimpleIoT** [comment]
**Symptom**: The Helium Non-VIP Dev Console is again passing sensor data.

**Description:** The Community Sensor Operator cannot confirm whether a fix has been implemented or not, but it appears that the critical part of console operations, which involves processing sensor data, is now working. However, a new issue has emerged regarding the organization's Data Credit accounting. Despite the Data Credit balance reaching zero, it appears that sensor data traffic continues to be processed without any effect on the Console's operations. The expected behavior is that when the Data Credit balance reaches zero, all sensor data traffic should not be actioned, and the Data Credit Used should not increment. The Community Sensor Operators are seeking confirmation regarding the correct operation of Data Credit, Sensor Data traffic management, and Data Credit rewards.

**Potential Consequences and Impact:**

1. **Data Credit accounting discrepancy:** The discrepancy in Data Credit usage when the balance reaches zero raises concerns regarding accurate cost management and billing for the organization. This can result in financial inaccuracies and affect the overall budgeting process.
2. **Inconsistent data traffic management:** The continued processing of sensor data traffic despite the Data Credit balance being depleted can lead to difficulties in managing and controlling data usage. This inconsistency hinders effective resource allocation and monitoring.
3. **Impact on Data Credit rewards:** The uncertain behavior of Data Credit and Sensor Data traffic management can affect the calculation of Data Credit rewards for Community Sensor Operators. This inconsistency can impact the incentives and benefits received by the operators.

**Expected Outcomes Sought:**

**Confirmation of correct Data Credit operation:** The Community Sensor Operators seek confirmation and clarification regarding the correct operation of Data Credit and Sensor Data traffic management. They require a clear understanding of how the Console should behave when the Data Credit balance reaches zero and how it impacts the processing of sensor data traffic.
**Resolution of Data Credit accounting issue:** It is crucial to resolve the issue related to Data Credit accounting and ensure that the Console accurately reflects the usage and management of Data Credits. This resolution is necessary for proper cost management and billing processes.

**Steps to Reproduce (if applicable):** Not applicable

**Priority:** **High**

**Affected Components:**

1. **Helium Non-VIP Dev Console**
2. **Data Credit accounting system**

**Comment by michaeldjeffrey** [comment]
The Dev Console is an internal testing environment. 
Very rarely does it match up with anything approaching Production. 
It can not used in a production like manner. 
There have been times in the past where individuals were invited to help test features in this environment. 
When that testing was done, the use of this environment should have ceased immediately.

**Comment by plainsimpleIoT** [comment]
Seems what I have described above is now an actual issue that you have only recently discovered? Trying to help but pretty annoying to be overlooked and then it turn into an actual concern 3 weeks later
