### ISSUE TITLE
Streamline OSS Build

### ISSUE THREAD

**Issue by lthiery** [helium/console#379]
There are some file edits required by the user. I wonder if we can automate/streamline this. 

Perhaps we copy the source into the build container and use `sed` to make these changes? 
Perhaps we can reference a `/config/docker.exs` instead of editing `/config/prod.exs`?

```
Follow instructions at the top of /config/prod.exs
Follow instructions at the bottom of /assets/webpack.config.js
Update host at the top of /config/releases.exs
```

**Comment by vicmgs** [comment]
@lthiery do we have any users deploying on their own domain? How did they modify their releases.exs file?

**Comment by vicmgs** [comment]
there will be releases-template.exs now
