### ISSUE TITLE
"Packets Transferred" on the Device page: "All Time" count off by one?

### ISSUE THREAD

**Issue by mfalkvidd** [helium/console#407]
![image](https://user-images.githubusercontent.com/893502/110308022-e3ca3500-7fff-11eb-9fad-985a6928f227.png)

"All Time" number is 2,631, while "last 7 days" is 2,632. "All Time" should be at least as high as the other numbers.

**Comment by vicmgs** [comment]
we should be fixing this in the next deploy, thanks.
