### ISSUE TITLE
How to change the console base url ?

### ISSUE THREAD

**Issue by disk91** [helium/console#419]
I would like the console to repond on localhost:4000/console/ to have it as part of a more global service. 
Is there a configuration I can use somewhere ?
not sure about ENV_DOMAIN if it can be use for this ?

**Comment by jdgemm** [comment]
Thanks, we're investigating.

**Comment by vicmgs** [comment]
There is no configuration for this. 

You would have to add the "/console" scope to `lib/console_web/router.ex` and `assets/js/Router.jsx` as well as update all links to in the front-end files to include the "/console" scope.
