### ISSUE TITLE
How to use wss instead of ws ?

### ISSUE THREAD

**Issue by disk91** [helium/console#430]
Websocket communications are on ws (not secured) is there a way to setup wss instead of ws ?

**Comment by vicmgs** [comment]
in the `/config/releases.exs` file, you would swap out the endpoint config on line 10 for something like the below snippet.

`config :console, ConsoleWeb.Endpoint,
  load_from_system_env: true,
  url: [scheme: "https", host: "example.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: secret_key_base`

**Comment by disk91** [comment]
Thank you, I'm testing it.

**Comment by disk91** [comment]
sounds like the console do not liked it:
Compile time configuration: nil
helium_console | Runtime configuration     : [rewrite_on: [:x_forwarded_proto]]
helium_console | 
helium_console | :force_ssl is a compile-time configuration, so setting
helium_console | it at runtime has no effect. Therefore you must set it in your
helium_console | config/prod.exs or similar (not in your config/releases.exs)
helium_console | and make sure the value doesn't change.

**Comment by mfalkvidd** [comment]
My console uses wss
![image](https://user-images.githubusercontent.com/893502/112732685-bbb55e00-8f3b-11eb-91f7-07bf263e7dfe.png)

This is line 12 in `config/releases.exs`: `url: [host: "mydomain.com", port: 443]`

This is my nginx proxy in front:
```
        location / {
                proxy_pass http://10.17.10.114:4000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
```
