### ISSUE TITLE
docker-compose file could use a ENV var for data location

### ISSUE THREAD

**Issue by disk91** [helium/console#452]
The docker compose file need to be modified like for
- DataBASE user/pass/dbname
- Data directory location
The use of environment variable for this would be really great

**Comment by michaeldjeffrey** [comment]
We're currently setting those in the docker-compose file
https://github.com/helium/console/blob/staging/templates/docker-compose-local.yaml#L20

Some work could be done to consolidate the DB env variables and the DB variables in the docker-compose file.
