### ISSUE TITLE
Integration HTTP fail on deployed instance of console

### ISSUE THREAD

**Issue by disk91** [helium/console#454]
Not clear why but the same HTTP integration working in console.helium.com is not working on my instance.
I just getting the following:
```
foxtrackr | error | Mar 20, 2021 9:08:54.428 PM | Integration Response
```
I propose to add the HTTP response code from the server.

My question here is : how to debug this kind of issues as there is no reason it comes from the backend side.

**Comment by macpie** [comment]
You should get more info than that in the debug mode, full request/response.

**Comment by disk91** [comment]
the debug does not provide much more information:
```
{
  "id": "0a9cc59c-2857-451e-a488-f5cc09cab0e1",
  "name": "foxtrackr",
  "status": "error"
}

{}
```

Any other traces ?

**Comment by disk91** [comment]
getting more in the router log (was thinking is was a console job to manage the integration)
[2021-03-23 13:29:53.429] <0.4155.0> [info] [c563e843-dc17-4fc2-9268-33aa4593b3b0] [router_http_channel:check_url:144] got bad dns record "xxxxxx" {notimp,{dns_rec,{dns_header,4,true,query,false,false,true,true,false,4},[{dns_query,"xxxx",a,any}],[],[],[]}}

**Comment by macpie** [comment]
Sadly, I could not reproduce in any of our servers or locally.
You could run this: 
```
docker exec -it helium_router _build/default/rel/router/bin/router remote_console

inet_res:resolve("XXX", any, a).
```

`XXX` being the url without `http(s)` and path (ex: `https://google.com/maps` -> `google.com`)

I would also take a look at your DNS setup on your server.

**Comment by disk91** [comment]
I'll try but as indicated when ping and curl this url from inside the router container I succeed in resolving it.

**Comment by macpie** [comment]
I would like to see the result with your HTTP integration's URL

**Comment by macpie** [comment]
FYI: we have an option https://github.com/helium/router/blob/master/src/channels/router_http_channel.erl#L105 to turn off the url check. It is not exposed via env variables but can be added here https://github.com/helium/router/blob/master/config/sys.config.src#L32

**Comment by disk91** [comment]
Command update 
inet_res:resolve("xxx.com",any,a).
{error,{notimp,{dns_rec,{dns_header,82,true,query,false,
                                    false,true,true,false,4},
                        [{dns_query,"xxx.com",a,any}],
                        [],[],[]}}}

**Comment by Vagabond** [comment]
What DNS resolver do you have configured for this system? does the 'dig' command work?

**Comment by disk91** [comment]
dig is not part of the router container but as described above :
From inside the container:
```
root@2f929337f7cf:/opt/router# ping  www.google.com
PING www.google.com (172.217.19.228) 56(84) bytes of data.
64 bytes from par21s11-in-f4.1e100.net (172.217.19.228): icmp_seq=1 ttl=108 time=13.3 ms
```

**Comment by macpie** [comment]
ability to disabled that check exposed here https://github.com/helium/router/pull/260

**Comment by disk91** [comment]
Tested working with the DNS check deactivation
