### ISSUE TITLE
Make possible to change the state_channel_amount 

### ISSUE THREAD

**Issue by disk91** [helium/console#465]
Would it be possible to setup the stat_channel_amount ? 
This could help to tune the state_channel duration.
Currently if I understand well, for every 2k DC payed by user to communicate, router needs to open a new SC that cost 35k DC so basically communication cost jumped x15 payed by router

**Comment by disk91** [comment]
Is that ROUTER_SC_OPEN_DC_AMOUNT parameter ?

**Comment by michaeldjeffrey** [comment]
That is the correct parameter for changing how much DC state channels open with.
