### ISSUE TITLE
FCntDown missing (on FCnt 0?)

### ISSUE THREAD

**Issue by lthiery** [helium/console#485]
Not sure what happened here. Looks like the first downlink (with ADRReq but no app payload) is missing the FCnt?

Unclear whether its Router (@macpie) or Console (@vicmgs)

![no_fcnt](https://user-images.githubusercontent.com/1606640/113204534-3a531980-9222-11eb-8f93-6cc8a0fa9d51.png)

**Comment by ambuznego** [comment]
@lthiery what's the `device_id`?

**Comment by lthiery** [comment]
> @lthiery what's the `device_id`?

@ambuznego `9a724cb0-d047-418d-87b1-070eaddcc6f1`

it's currently still in the event buffer on the dashboard too

**Comment by ambuznego** [comment]
Addressed in last release.
