### ISSUE TITLE
Downlink URL is localhost:4000

### ISSUE THREAD

**Issue by disk91** [helium/console#489]
The downlink URL in integration is http://localhost:4000/api/v1/down/0a...
Even if the domain seems to be setup to the right one on the configuration files.

Can you help to find where to correctly setup this please ?

**Comment by vicmgs** [comment]
If you have ENV_DOMAIN env var filled in with your domain, it should replace localhost:4000

**Comment by disk91** [comment]
Env file changed, 
container restarted
```
ENV_DOMAIN=https://helium-iot.eu
```
No change, the integration donwlink is still localhost:4000 even for new integrations created

**Comment by vicmgs** [comment]
your env_domain should be "helium-iot.eu"

I'm not sure what is happening on your machine but we have it working on our setup. 

We will be releasing a new open source version this afternoon but nothing regarding this is updated.

**Comment by disk91** [comment]
It works after updating the console.
apparently, it's better to remove container to ensure the conf file is re-considered a least on Centos
