### ISSUE TITLE
Enhance HTTP Integration for Query Parameters

### ISSUE THREAD

**Issue by arkieguy** [helium/console#509]
Allow creation of dynamic URIs - the base url + the query string or REST parameters.  For example:

https://example.com?t=72.6&p=26.1&h=80.72
https://example.com/t/72.6/p=26.1/h/80.72

Where the values of the query parameters are dynamically  populated from the console data (incoming payload, etc.).

I can think of several ways this might be accomplished:

- Via an interface like “Add Headers” for “Add Query Parameters” with a key value pair.  The value field would need to support static text or allow for mapping of anything in the current payload object.
A good example of similar functionality is available in [PipeDream.com](https://pipedream.com) for the "send_http_request" step  - [screen shot](https://pasteboard.co/JWsndex.png));
- Modify the “Function” to have a predefined object for “QueryParms” that could be extended via JavaScript to automatically add the resulting query to the url.
- Allow for templating on the “Endpoint URL” (https://example.com?t={decoded.temp},p={decoded.press},user={header.userId})

**Comment by jdgemm** [comment]
Can you describe what you're wanting to accomplish with this request?

**Comment by jdgemm** [comment]
internal id: 9899

**Comment by jdgemm** [comment]
added to upcoming release
