### ISSUE TITLE
Add 'Prebuilt Integration' for Pipedream

### ISSUE THREAD

**Issue by davetapley** [helium/console#514]
Hi, would you accept a PR to add a 'Prebuilt Integration' for https://pipedream.com/?

Corresponding issue over there: https://github.com/PipedreamHQ/pipedream/issues/1165

**Comment by jdgemm** [comment]
Yes, @davetapley will accept, also can you share official pipe dream logo, thanks.

**Comment by jdgemm** [comment]
also @davetapley can you provide more details on how you're planning on using integration

**Comment by davetapley** [comment]
@jdgemm sure:
Pipedream lets you run Node.js code and connect together different APIs.

Currently I have it writing out [a GPS tracker's location](https://www.digitalmatter.com/devices/yabby-gps/) to a Google Sheet, and sending a text with Twilio when `inTrip` goes true.

I'm sure there are lots of other use cases to be found 😁 

![](https://res.cloudinary.com/pipedreamin/image/upload/v1611342232/docs/pipedream_workflow_diagram_etqerj.png)
