### ISSUE TITLE
HTTP integration doesn't work with "&" inside of URL

### ISSUE THREAD

**Issue by slavendam** [helium/console#519]
When I add some URL to HTTP integration, which have "&" inside, changes it to "&amp;"

So for example 
"https://myapp.com?par1=val1&par2=val2" after adding to integration will be changed to 
"https://myapp.com?par1=val1&amp;par2=val2"

And server than make integration request to this second URL which is wrong (not recognized).
Can you disable this kind of formating?

Thanks

**Comment by vicmgs** [comment]
fix will be released this week

**Comment by jdgemm** [comment]
internal id: 9885
