### ISSUE TITLE
Negative FCnt

### ISSUE THREAD

**Issue by lthiery** [helium/console#526]
![unknown](https://user-images.githubusercontent.com/1606640/115120904-c5434c00-9f64-11eb-9425-9fe73202fc86.png)

Very fishy. Not sure what's going on here, but this is impossible.

**Comment by simonsaysjake** [comment]
Update: happened multiple times. Screenshot: 
![image](https://user-images.githubusercontent.com/12376742/115156621-1467aa80-a053-11eb-8386-ca09a7640ab1.png)
