### ISSUE TITLE
Device page: adding new or changing names requires page refresh to see updated values

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#529]
Screen needs to refresh when changing data on screen, including what labels are attached, names of devices, and even new devices

**Comment by vicmgs** [comment]
@simonsaysjake which console environment are you noticing this on? which URL?

**Comment by vicmgs** [comment]
also, which device page? index or show page?

**Comment by simonsaysjake** [comment]
https://console.helium.com/
I notice it a lot on devices and labels pages, usually when theres a list of devices - does not happen on the individual device screen

**Comment by vicmgs** [comment]
can you list out the exact workflows you are using that causes these behaviors? Im confused because you cannot edit names on the device list page, adding a new device on the device list page works for me etc.

**Comment by simonsaysjake** [comment]
Adding a label, adding/removing an integration on a label, etc. I'll look out for more scenarios and try to get screenshots

**Comment by vicmgs** [comment]
Thank you. This was an issue before with a different npm package, but now it should be working consistently with raw socket triggers on the front-end.
