### ISSUE TITLE
Devices page: Horizontal scroll when left sidebar is open

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#530]
Cannot show screenshot due to private device list - ping me for a screenshot as needed.

When left sidebar is open, device on/off slider and trash/delete icon are off the page due to horizontal scroll

**Comment by vicmgs** [comment]
right, and you would scroll to reach them, or update the columns you want to view

**Comment by vicmgs** [comment]
just found the issue, apparently its a narrow range of page widths that do this and I couldn't tell with my monitors

**Comment by vicmgs** [comment]
can I get a screenshot or a video from you actually? I just realized i was able to reproduce on a separate branch that isn't deployed on console.helium.com, meaning it isn't the issue you are seeing here. victor@helium.com

**Comment by simonsaysjake** [comment]
Sent!

**Comment by vicmgs** [comment]
worked out issue with simon over email, not a bug
