### ISSUE TITLE
Empty Frame Count and No Integration Request

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#542]
![image](https://user-images.githubusercontent.com/12376742/115574408-96dcae00-a28f-11eb-8f1a-ec3a00ae7c76.png)

See screenshot. Frame 7 is listed as blank. The blank frame also lists "Integration Request" as "error" - even though the integration response is rejecting (expected), the request on the other frames does show success in at least requesting.

**Comment by simonsaysjake** [comment]
FYI this is what the others look like
![image](https://user-images.githubusercontent.com/12376742/115575310-719c6f80-a290-11eb-9fac-ad0f821b854e.png)

**Comment by ambuznego** [comment]
@simonsaysjake thanks for reporting. I do need a little more information. do you mind emailing me the `deviceId` for which you took this screenshot at [alejandra@helium.com](mailto:alejandra@helium.com)? I take a bit of a deeper look on our end.

**Comment by simonsaysjake** [comment]
Sorry, I'm unsure of which device it was and the history has since been overwritten. I can raise the issue again if it happens after the latest update.
