### ISSUE TITLE
Feature request : Clear downlink request as part of the downlink response

### ISSUE THREAD

**Issue by disk91** [helium/console#553]
It would be great in the downlink response to get the ability to request a downlink queue cleanup for a given device.
This makes sense when the previously queued message does not make sense or the one you want to push now have a high priority and need to be executed immediately.

**Comment by vicmgs** [comment]
this can be down in the downlink sidebar on the device page

**Comment by disk91** [comment]
This was not my point.
I was talking about making a clear request from the backend.
By adding a field in the downlink payload structure to request the console to clear the queue remotely.

**Comment by disk91** [comment]
open in router as requested from discord discussion
