### ISSUE TITLE
Downlink payload sets 3 queued messages

### ISSUE THREAD

**Issue by pooley92** [helium/console#556]
Payload was sent from the devices page. 
The payload was sent in text form as it was already base64 encoded. 
The device has 2 integrations attached at the time. 

<img width="653" alt="Screenshot 2021-04-22 at 23 43 11" src="https://user-images.githubusercontent.com/75324434/115794076-3cde0480-a3c5-11eb-9560-627e86d2af59.png">
<img width="634" alt="Screenshot 2021-04-22 at 23 41 14" src="https://user-images.githubusercontent.com/75324434/115794081-3f405e80-a3c5-11eb-8433-adbbf6e50a89.png">

**Comment by vicmgs** [comment]
@pooley92 what is your device-id that you are downlinking?

**Comment by pooley92** [comment]
Device EUI is 0080000004025AC5

**Comment by vicmgs** [comment]
this should be fixed with latest release
