### ISSUE TITLE
Add Microshare Prebuilt Integration

### ISSUE THREAD

**Issue by Adigi** [helium/console#558]
Name of Application: Microshare

Required Inputs: {token}

Integration Type: HTTP

Endpoint: https://ingest.paks.microshare.io/share/io.microshare.helium.packed/token/{token}

HTTP Headers
Accept: application/json
Authorization: Bearer {token}

**Comment by Adigi** [comment]
I'm adding here a link to the Microshare Logo: https://www.microshare.io/microshare-logo-files/
"Logo | Blue Background  |  White Text  | No Tagline  |  png" could be used for the PreBuilt Integration

**Comment by vicmgs** [comment]
going into next release
