### ISSUE TITLE
"Unknown Decoder" Error

### ISSUE THREAD

**Issue by nickhough** [helium/console#560]
When creating a Function using a Custom Script, a space between `Decoder` and `(` will cause the Decoder to fail.

This works: `function Decoder(bytes, port) {`
This doesn't: `function Decoder (bytes, port) {`

**Comment by vicmgs** [comment]
Can you share the entirety of your function? We dont think that space is the issue

**Comment by nickhough** [comment]
@vicmgs 

Here's a link to the Decoder: https://api.helium.vision/decoders/glamos-decoder.js

**Comment by nickhough** [comment]
@vicmgs

Upon further testing, I can only duplicate the issue when I paste a decoder from my machine into Console with the extra space. When I try to utilize the Function, I receive this...

```
...
"decoded": {
      "error": "unknown_decoder",
      "status": "error"
  },
...
```

I then edit the Function, delete the "extra" space, save and try again and it works.

```
...
"decoded": {
    "payload": {
        "antenna": 0,
        "position": {
            "altitude": 833,
            "lat": "43.5900994",
            "lng": "-116.2009297"
        }
    },
    "status": "success"
},
...
```

**Comment by vicmgs** [comment]
can you share a working payload as well

**Comment by nickhough** [comment]
@vicmgs 

Base64: vf6rLV5EA0EA
Hex: bdfeab2d5e44034100

They successfully parse, regardless of the "extra" space.
