### ISSUE TITLE
Add ABP strategy (Activation by Personalization)

### ISSUE THREAD

**Issue by Synthex-Moon** [helium/console#567]
Add ABP strategy (Activation by Personalization) 

There are advantages to ABP, for devices whose security is not essential. 
It's a simple TX without RX, which allows simpler devices, with inefficient antenna. 

The communication is shorter, so the battery is less solicited. 

In addition, the main competitors allow to make this strategy (Objenious, TTN, ...)

**Comment by jdgemm** [comment]
Currently we have no plans for ABP due to security concerns, but if there's heavy demand we'll re-consider.
