### ISSUE TITLE
Downlink queue shows blank payload

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#573]
<img width="610" alt="Screen Shot 2021-04-29 at 11 22 45 AM" src="https://user-images.githubusercontent.com/12376742/116576282-6a531280-a8dd-11eb-9425-13d06c1091a7.png">

After submitting downlink, queue shows pending downlink, but does not show the message. Only shows a ','

Issue does not resolve after page reload or additional downlink.

**Comment by vicmgs** [comment]
@michaeldjeffrey need your help looking into this...

**Comment by vicmgs** [comment]
@simonsaysjake the issue here is that since you chose to send a pre-encoded payload of "AQABLA==" to your device, our router then replies with the decoded payload but then encodes it into UTF8, which is the "   ," string you see above. We will work on making this less confusing.

**Comment by simonsaysjake** [comment]
@vicmgs it's Base64 encoded which is what we've been told we need to do to send a hex string down to the device. Is that not correct? Either way, the queue should show what we inputted, right?

**Comment by vicmgs** [comment]
@simonsaysjake The sending of the message to the device is correct, the displaying of your input in the queue is failing here

**Comment by vicmgs** [comment]
fix should have been released
