### ISSUE TITLE
No payment options for auto renewal

### ISSUE THREAD

**Issue by mfalkvidd** [helium/console#575]
There are no payment options available when I try to add automatic renewals.

![BF49598E-92C8-4E18-876A-61DC1D03452F](https://user-images.githubusercontent.com/893502/116612073-6358ee00-a937-11eb-8ebe-640a004bc613.png)

**Comment by vicmgs** [comment]
is this on console.helium.com? Also, have you purchased DCs in this organization already? If not, you do not have a default payment method, thus the empty list here.

**Comment by mfalkvidd** [comment]
Yes it on console.helium.com
No I have not purchased DCs already. That’s what I am trying to set up.

**Comment by vicmgs** [comment]
You can set up automatic purchases only after purchasing DC for the first time with a card successfully.

**Comment by jdgemm** [comment]
Right, so as you said Console should only make automatic renewal successful after successful cc purchase.

**Comment by vicmgs** [comment]
fix coming next release
