### ISSUE TITLE
Add "Pre-built Integration" for Initial State IoT Dashboard

### ISSUE THREAD

**Issue by rkuhlman** [helium/console#600]
1. Are you using Helium hosted Console or running your own open source Console? Helium

2. If you are on Helium hosted Console, which url are you currently on? console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753). N/A

Please describe your issue:
I am the head of Product at Initial State, a streaming IoT dashboard recently acquired by Tektronix. We would like to explore the ability for Initial State to be included in the pre-built integration in the Helium console. I have ordered a Lora test device, which is on it's way. I will be starting testing to understand feasibility. However, I have no doubt, that we will be able to get it working and that it would be a great addition to the list of pre-builts. 

Check out Initial State here - initialstate.com

Would love to understand next steps.

**Comment by jdgemm** [comment]
Please provide details technically on what would be required (http vs mqtt, authentication token, etc)...

**Comment by rkuhlman** [comment]
Basics: 

- The API uses HTTP (RESTful) to send data. It can also function using URL parameters, but that is not great for best-in-class implementations.  
- Here is the API document. It is a pretty straightforward. - https://initialstateeventsapi.docs.apiary.io/#reference/event-data 
- The end user generates a revokable token inside their account to authenticate with the service in the API. 

Basics Flow: 
1. User Creates an "Access Token" for their account. 
2. User uses the browser UI or API to create a "Bucket" in Initial State. 
3. User uses HTTP API to send data to the newly-created bucket using the "Access Key," "Bucket Key," and a JSON-structured set of Key/value data points, where Key = Channel Name and Value = New Data Point Value. 
4. User can arrange and create multiple real-time dashboards around this incoming data. 

You can start a free trial really quickly here: initialstate.com to do some qucik prototyping if you like.
