### ISSUE TITLE
Can you please add the LoRaWAN DR or SF for each uplink/DL packet ?

### ISSUE THREAD

**Issue by pdvaneijk** [helium/console#635]
Hi,

Can you please add the LoRaWAN DR or SF/frequency info in the drop down message for each uplink or downlink ? That makes debugging a whole lot easier. All other LoRaWAN LNS consoles show this data.

Thanks!

Patrick

**Comment by jdgemm** [comment]
The SF/Frequency is available in the Event Log for each device. Click the "+" sign and click Hotspots.
