### ISSUE TITLE
LoRaWAN CFList in Join Accept ?

### ISSUE THREAD

**Issue by pdvaneijk** [helium/console#636]
I am not able to find any documentation on the format of you Join Accept. Are you sending the Channel Frequency list as part of the Join Accept to tell the LoRaWAN device which channels to use ?

I am loosing a large amount of traffic on my LR1110 based tracker and I assume it is because it is trying to use all 64 channels.

**Comment by JayKickliter** [comment]
Joining is handled by https://github.com/helium/router
