### ISSUE TITLE
add event and integration data to API

### ISSUE THREAD

**Issue by tedder** [helium/console#637]
I'm using the Helium hosted console. It would be nice if the API exposed much of what is in the web console. Specifically:
- add summary data to "list devices", e.g, packets xfered, DC used, last connected, 
- list device events
- get integration message for event (eg request/response/error)

Per [the docs](https://docs.helium.com/api/console/) none of this is supported. Just basic CRUD for a device.

**Comment by jdgemm** [comment]
Thanks we'll add to our backlog after Console 2.0.

**Comment by jdgemm** [comment]
The team has questions about this last request:

`get integration message for event (eg request/response/error)`

Can you provide additional context and/or examples of what you're expecting and how you would use this API?

**Comment by tedder** [comment]
Hi- it's the messages in this screenshot that I'd like to be able to access. I was pulling up this example and saw it errored out- I didn't know until I checked the UI. Having an endpoint showing this log would allow me to monitor it.

![Screenshot from 2021-08-31 15-06-16](https://user-images.githubusercontent.com/97914/131582035-d32e6399-1a1a-4fd2-a713-8536c7154973.png)

**Comment by vicmgs** [comment]
coming next release
