### ISSUE TITLE
Share AWS IOT core for lorawan device registry

### ISSUE THREAD

**Issue by eszymko** [helium/console#640]
We would like to have a way to say to helium network to use the device registered in AWS IoT core for lorawan.
Say differently is like using AWS lorawan join server to register the device.
The use case is to extend AWS IOT core lorawan networks with Helium networks.
This feature is called passive roaming in the lorawan spectification.

**Comment by PharkMillups** [comment]
Hi Eric. Thanks for the issue. Just to clarify, what's your target LNS here? 

Also, send me an email. It would be cool to learn more about Pilot Things (mark@helium.com)

**Comment by jdgemm** [comment]
Closed as discussions with biz dev ongoing.
