### ISSUE TITLE
Notifications for labels are not sending

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#647]
1. Are you using Helium hosted Console or running your own open source Console?
Helium console 

2. If you are on Helium hosted Console, which url are you currently on? 
main tenant (not testing)

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
N/a for now 

Please describe your issue:
Notifications for labels are not sending. I had one turned on for “when device stops transmitting for 1 hour” and it has not been sending for any devices that do not report. Each one of my devices does have two labels but I only have the notifications turned on for one of the labels. The use case should work that I still get the notification, but maybe there’s a conflict with two?

**Comment by vicmgs** [comment]
I just found that if a device goes inactive more than once in a 24 hour period, only the first time it goes inactive in the 24 hour period will the emails trigger. Does this sound like the bug you were experiencing, or did you simply not receive any emails for these devices whatsoever?

**Comment by vicmgs** [comment]
@simonsaysjake just pushed fix to prod console, you should be seeing emails now

**Comment by simonsaysjake** [comment]
Yup, got a bunch that are old. Probably stuck in a queue. 

Thanks!
