### ISSUE TITLE
Console display blank welcome page after login with 2FA

### ISSUE THREAD

**Issue by disk91** [helium/console#648]
1. Are you using Helium hosted Console or running your own open source Console?
Own opensource consoel

2. If you are on Helium hosted Console, which url are you currently on? 
console.helium-iot.eu

Please describe your issue:
After Login on AUTH0 with 2FA activated, the next page is a blank page ; when refreshing the welcome page is printed. This is not a new issue, I always have it. I was waiting for a fresh console update to report it being sure it hasn't been fixed.

**Comment by vicmgs** [comment]
How did you turn on 2fa for your deployment of console? This was not something we enabled in the open source release

**Comment by disk91** [comment]
This is a Auth0 option, I consider this as an important feature to be activated. 
You should take a look at it as there is no big impact on the console. But currently when this is enabled, the welcome page is blank and just come back when refreshed.
The only error I see in JS console is:
Uncaught (in promise) TypeError: tokenClaims is undefined
To bypass this issue, we need to check "Remember me for 30 days" in the 2FA popup after this the console displayed correctly.

**Comment by vicmgs** [comment]
after testing personally, this looks like a bug in auth0. I have submitted a ticket in their support queue.

**Comment by disk91** [comment]
Thank you !
