### ISSUE TITLE
Missing db schema upgrade when upgrading the console

### ISSUE THREAD

**Issue by disk91** [helium/console#649]
1. Are you using Helium hosted Console or running your own open source Console?
Running my own console

2. If you are on Helium hosted Console, which url are you currently on? 
console.helium-iot.eu

Please describe your issue:
After upgrading the console, I'm getting error 500. It seams that the database schemas has not been migrated to support the new version:
```
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42703 (undefined_column) column o0.default_app_eui does not exist

    query: SELECT o0."id", o0."name", m1."role", o0."dc_balance", o0."inserted_at", o0."default_app_eui" FROM "organizations" AS o0 INNER JOIN "memberships" AS m1 ON m1."organization_id" = o0."id" WHERE (m1."user_id" = $1)
        (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
        (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
        (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (console) lib/console_web/controllers/organization_controller.ex:23: ConsoleWeb.OrganizationController.index/2
        (console) lib/console_web/controllers/organization_controller.ex:1: ConsoleWeb.OrganizationController.action/2
        (console) lib/console_web/controllers/organization_controller.ex:1: ConsoleWeb.OrganizationController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```
Is there something to upgrade the DB schema ?

**Comment by vicmgs** [comment]
I don't have issues with this running my own open source console, what commit are you trying to upgrade to?

**Comment by vicmgs** [comment]
i just re-ran my local open source console, migrations scripts are called when "docker-compose up" is executed.

**Comment by vmalepati1** [comment]
The migration scripts are indeed called when building with Docker. However, the slight inconvenience is that when there is an already-existing database, the tables need to be manually altered. If this process could be automated, it would be more seamless to upgrade the console.

**Comment by vicmgs** [comment]
@vmalepati1 they should not need to be manually altered, the column changes happens when "docker-compose up" is executed.

that's what line 16 of entrypoint.sh is doing

**Comment by vmalepati1** [comment]
Got it. In that case this issue should be closed.

**Comment by vicmgs** [comment]
👍

**Comment by disk91** [comment]
In my context, the database has not been upgraded during docker compose. I don't know why and I did not noticed an error in the docker-compose build. docker-compose up did not update the DB.

**Comment by vicmgs** [comment]
errors would show up during the up phase for the migrations, not the build phase. Something to keep an eye on in the future if it doesn't work
