### ISSUE TITLE
Sorted Date should put Blank as Oldest

### ISSUE THREAD

**Issue by lthiery** [helium/console#650]
1. Are you using Helium hosted Console or running your own open source Console?

Hosted

2. If you are on Helium hosted Console, which url are you currently on? 

https://console.helium.com/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

NA

Please describe your issue:

Dates sorting puts blanks as most recent. I think the general use-case is that "I want to see the most recent" so I would put blanks as "oldest", not "newest".

![image](https://user-images.githubusercontent.com/1606640/122072648-9ef72c80-cdac-11eb-92ca-c1a68513da68.png)

**Comment by vicmgs** [comment]
going into next release
