### ISSUE TITLE
Enhancement - database migration scripts

### ISSUE THREAD

**Issue by disk91** [helium/console#651]
It seems there is no database migration scripts. Some new releases are adding columns, these addition makes the console nor correctly working because the database schemas becomes outdated.
A migration script would help to fix that.

**Comment by vicmgs** [comment]
migration scripts are all in priv/repo/migrations. Our staging environment is built like an open source console and it runs the migration scripts fine.

**Comment by vicmgs** [comment]
closing in favor of https://github.com/helium/console/issues/649

**Comment by disk91** [comment]
You are lucky, my production environment hasn't been updated. And I had to do it manually.

**Comment by vicmgs** [comment]
i guess its all luck for me
