### ISSUE TITLE
Live packet 'no integration' key showing wrong status

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#652]
![image](https://user-images.githubusercontent.com/12376742/122088901-36bc4100-cdd4-11eb-9296-e3cae891e1b1.png)
![image](https://user-images.githubusercontent.com/12376742/122088980-4b98d480-cdd4-11eb-8ba9-1f6f5bcee750.png)

2 images attached. 

You can see that on the first one, the ping dot is red, indicating no integration, but the integration is totally there and working fine. Upon hard refresh of screen (second screenshot), dot is blue, indicating it's fine all along. 

I do not have a screenshot but I've also seen similar patterns with the yellow dot, even though it is fine.

FYI this device has 2 labels, one has an integration attached, one does not.

**Comment by vicmgs** [comment]
@simonsaysjake The chart updates on a 5 second interval. I think if you saw the red dot and waited a few seconds, the dot will turn blue automatically if the integrations are successful. Let me know if that is the case and if that works for you, otherwise we can look into it further.

**Comment by simonsaysjake** [comment]
@vicmgs That was not what I was seeing and what I've seen in the past. It was definitely more than 5 seconds to load the page, see the red dot, look for more info by clicking the plus then the Integration Messages, then take a screenshot

**Comment by simonsaysjake** [comment]
Though I do not see the issue replicating right now

**Comment by vicmgs** [comment]
that is very weird, did you grab the screenshots yesterday?

I will test some edge cases on my end. In the meantime, please keep an eye out for it happening again.

**Comment by simonsaysjake** [comment]
yup yup - a few mins before I uploaded

**Comment by simonsaysjake** [comment]
I can BOLO for it again

**Comment by vicmgs** [comment]
yes please, thank you

**Comment by vicmgs** [comment]
@simonsaysjake found the issue on my end, this should not be a problem anymore
