### ISSUE TITLE
Opening device detail in new tab has strange behavior

### ISSUE THREAD

**Issue by simonsaysjake** [helium/console#653]
**Scenario:**
I am on a label's list of devices page. I want to open a device in a new tab so I can look at it while maintaining my previous screen (especially if I am opening multiple devices at the same time, or have debug turned on). If I right click on the device and select 'open in new tab' or 'open in new window', it works as it should - the label device list page stays the same and another tab/window opens with the device specific page.

**Error:** 
If I use cmd/ctrl click (common way to open link in a new tab) on a specific device to open it in a new tab, it will load the _current_ page with the selected device, but open a _new tab_ for the original label device list page that was already open. The problem with this is that it reloads the label device list page, losing any current view (i.e. debug window closes and clears, multiple devices are selected, cannot then open another device detail page with another cmd/ctrl click).

**Note:** This is not just the labels page - it seems to happen all around console.

**Environment:** 
Mac OSX - Chrome and Safari (both up to date) show the same bug. That being said, I've noticed this for a very long time, so it's not necessarily a recent update.

**Happy to screen share with anyone if that would be easier to show.**

**Comment by jdgemm** [comment]
Thanks for reporting, we've added to our backlog and will follow up with you if necessary.

**Comment by jdgemm** [comment]
Jay we've fixed this on staging and will include in upcoming release.

**Comment by vicmgs** [comment]
fix releasing to master tomorrow
