### ISSUE TITLE
Link to help on multiple packets is missing #Staging

### ISSUE THREAD

**Issue by pe1mew** [helium/console#673]
At Helium hosted Console: https://staging-console.helium.wtf/multi_buys/new
Organisation RFSee

Please describe your issue:

In "Multiple Packets
You can purchase duplicate packets if multiple Hotspots hear the device.
**Learn more about Multiple Packets**"

The link **Learn more about Multiple Packets** is not linking to help

**Comment by ambuznego** [comment]
@pe1mew Once we have updated documentation, this link will be updated. Thanks for reporting.

**Comment by ambuznego** [comment]
This has been updated and released to prod.
