### ISSUE TITLE
Staging UI: Icons without text descriptions of their actions

### ISSUE THREAD

**Issue by rjmendez** [helium/console#674]
1. Are you using Helium hosted Console or running your own open source Console?

Hosted, staging console.

2. If you are on Helium hosted Console, which url are you currently on? 

https://staging-console.helium.wtf/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Some icons don't provide any clues as to what they are for via visible text on the objects themselves or a contextual menu when hovering a cursor over them. This should be a simple enhancement that would help new users without context or experience with the console navigate.

Examples:

How would a new user know what these icons do? How would I explain it to them without a screenshot?
![newdevice_newlabel](https://user-images.githubusercontent.com/16153374/124187617-b4927480-da83-11eb-8d7d-0567f7ebab79.png)

This seems like a great way to go about this.
![hover_text_hint](https://user-images.githubusercontent.com/16153374/124187781-ee637b00-da83-11eb-907f-587d639d0849.png)

**Comment by ambuznego** [comment]
@rjmendez Thanks for pointing this out! We've made some changes to address this. It's now live on staging.

**Comment by JakeSwinn** [comment]
@rjmendez thank you for your help testing and providing feedback for Console 2.0! You've been selected to receive a promo code for some Helium swag (as mentioned in our blog: https://blog.helium.com/console-2-0-beta-test-and-earn-swag-ee366734779 ). Do you have a preferred email address where you would like your promo code sent? Thanks again for your hard work!

**Comment by JakeSwinn** [comment]
@rjmendez sorry, just realized that github blocks out email addresses.  if you are on the Helium discord server, you can send me your preferred email there...my handle is @ Swinnward.  Thanks, and let me know if you have any questions!

**Comment by rjmendez** [comment]
Awesome, thanks!
