### ISSUE TITLE
502 Bad Gateway on first few attempts to utilize.

### ISSUE THREAD

**Issue by HNT-Hub** [helium/console#675]
1. Are you using Helium hosted Console or running your own open source Console?
Staging Console

2. If you are on Helium hosted Console, which url are you currently on? 
https://staging-console.helium.wtf

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
No device integrated yet, cannot access staging console.

Please describe your issue: In the first few attempts to utilize staging I keep getting blank pages. I already have had an account with a device integrated in the past as well (mapper/field tester). I then removed it in order to have a fresh slate for staging console 
![Screenshot 2021-07-02 120320](https://user-images.githubusercontent.com/83094770/124307493-c116db80-db1c-11eb-9fdd-3db0ed9c89a7.png)
2.0.

@stagingconsole

**Comment by vicmgs** [comment]
Hi there, you were likely attempting to log in while we were pushing a fix. We had to down staging for a few minutes this morning
