### ISSUE TITLE
Staging UI Tweeks: Device Name

### ISSUE THREAD

**Issue by NTech242** [helium/console#677]
1. Are you using Helium hosted Console or running your own open source Console?

- Hosted

2. If you are on Helium hosted Console, which url are you currently on? 

- https://staging-console.helium.wtf/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Would be good to keep the device name at the top and in bold like previously done, my eyes are running around trying to figure out which device I am on.

![image](https://user-images.githubusercontent.com/86085021/124527239-20057a80-ddd3-11eb-99d9-5358d674098b.png)

**Comment by ambuznego** [comment]
@NTech242 Thanks for pointing this out! We've made some changes to address this. It's now live on staging.

**Comment by NTech242** [comment]
Glad to help, I have an idea to help with navigation, should I make a new post or sending it to you here is fine?

**Comment by ambuznego** [comment]
@NTech242 New issue would be best, thanks!

**Comment by JakeSwinn** [comment]
@NTech242 thank you for your help testing and providing feedback for Console 2.0!  You've been selected to receive a promo code for some Helium swag (as mentioned in our blog:  https://blog.helium.com/console-2-0-beta-test-and-earn-swag-ee366734779 ).  Do you have a preferred email address where you would like your promo code sent?  Thanks again for your hard work!

**Comment by NTech242** [comment]
Oh awesome thank you! You can send it to ***@***.***

I'm sure I will have more suggestions as we continue to use console. Thanks again and we look forward to working with you.

TEST
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by JakeSwinn** [comment]
@NTech242 looks like github blocks out the email addresses.  are you on the Helium discord server?  you can send me your email on there...my handle is @ Swinnward
