### ISSUE TITLE
Staging - Console is not responsive to mobile screen

### ISSUE THREAD

**Issue by parthAirspace** [helium/console#681]
Please describe your issue:

Im not sure if this is a valid issue, as i dont know how many users prefer to use mobile device to check console but thought worth mentioning. 

<img width="721" alt="Screen Shot 2021-07-06 at 4 55 32 PM" src="https://user-images.githubusercontent.com/80001482/124680454-50085880-de7b-11eb-89f9-4227b0a42d47.png">
<img width="1221" alt="Screen Shot 2021-07-06 at 4 58 08 PM" src="https://user-images.githubusercontent.com/80001482/124680475-5ac2ed80-de7b-11eb-9cf7-56195f02a17b.png">

**Comment by vicmgs** [comment]
Hi, thank you for reporting. We are aware of this issue and will make this a priority after the migration to prod is complete.

**Comment by AkosLukacs** [comment]
One additional note: If you hide the mobile browser's status/address bar, the newly available space is not used by the console UI.
The yellow area in the screenshots below. It's more significant in landscape mode, on a different phone the empty space felt like about 1/3 of the whole screen.

In portrait mode:
![image](https://user-images.githubusercontent.com/844331/132084944-78c6df1d-7972-40ec-85b7-e6ccc7c267bb.png)

In landscape mode:
![image](https://user-images.githubusercontent.com/844331/132084971-fab9410a-2381-440c-9a2f-3ea85d8077e3.png)

**Comment by vicmgs** [comment]
closing as duplicate
