### ISSUE TITLE
Make Initial organization dc balance as a parameter

### ISSUE THREAD

**Issue by disk91** [helium/console#683]
1. Are you using Helium hosted Console or running your own open source Console?
OSS

2. If you are on Helium hosted Console, which url are you currently on? 
helium-iot.eu

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Evolution, It would be good to be able to setup the initial org dc_balance with a env parameter
The 10.000 are hardcoded in lib/console_web/controllers/organization_controller.ex and could be replaced by an env variable with a default value 10000.

**Comment by vicmgs** [comment]
ok, we will make this possible after console 2.0 goes to prod

**Comment by vicmgs** [comment]
closing, will be deployed to prod soon

use INITIAL_ORG_GIFTED_DC .env variable

**Comment by vicmgs** [comment]
deployed to prod along with console 2.0, check the latest release notes for upgrade instructions
