### ISSUE TITLE
Staging Console: Label / Device Navigation

### ISSUE THREAD

**Issue by NTech242** [helium/console#684]
1. Are you using Helium hosted Console or running your own open source Console?
Helium hosted

2. If you are on Helium hosted Console, which url are you currently on? 
https://staging-console.helium.wtf/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

When having a group of devices under one label, it would be more efficient to be able to have a nested pane, listing all devices under a label, if possible, so that when you are done viewing one device in a label group, you do not have to click that label again then select the next device.

**Comment by vicmgs** [comment]
Hi, I am not fully understanding your recommendation. Can you please be more specific about which page and which component you are referring to?

**Comment by vicmgs** [comment]
I think I understand now, thanks.

**Comment by jdgemm** [comment]
Closing this issue given other higher priorities and work needed to save a click.
