### ISSUE TITLE
No uplink traffic after Join Accept

### ISSUE THREAD

**Issue by pdvaneijk** [helium/console#689]
I am running on the staging console under the Semtech organization with 2 tracker devices:

21867dfd-30d0-4054-9495-afb3180abc98

a7609123-e6c9-4543-b82a-c29a5b3ba74a

They were working perfectly fine before 7/1, but when I can back from the long weekend the devices now only JOIN and then nothing. No additional uplink traffic shows up in the console. Nothing has changed on the trackers as far as settings or FW goes.

**Comment by lthiery** [comment]
@pdvaneijk we noticed some issues with CFList last week and disabled it by default on Friday (7/9). We're working on making it possible to enable selectively (default off). I'm not sure what changed since 7/1 yet, but can you try a reset of the device and see if anything is different with Fridays' change?

**Comment by pdvaneijk** [comment]
OK thanks for the info. I just reset both devices. I did notice that the ADR function was suddenly turned off on my devices . That of course prevents the device from receiving the correct channel list (assuming you do not send the CFlist in the join Accept. I turned ADR back on for my devices, one of them is working again as it should. The other one I am sure will come back too.

**Comment by lthiery** [comment]
@pdvaneijk Well we only disabled the CFList since Friday, so unsure why they stopped working on the 1st then... Let's test this again once we have CFList as an option the user can enabled. With that, you should be able to keep ADR disabled but for now, we do again rely on it for channel masks.

**Comment by pdvaneijk** [comment]
@lthiery, sorry for not being more clear. I actually did not test till Friday July 9th, some time in the afternoon.

**Comment by lthiery** [comment]
@pdvaneijk Ah excellent! That definitely clarifies. It was probably because of the CFList getting disabled and the ADR being disabled on the device then. I'll ping you as soon as we have CFList re-enabeld

**Comment by vicmgs** [comment]
closing as CFlist label setting is available on prod
