### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by weirongbo** [helium/console#695]
The following error was reported when I used the API KEY to GET. Could you please tell me how to solve this problem?
$ curl -G -H "weirongbo:RbTpB/Lv6R7vlKwRDOjGEM/SNLqvHdSuynnAcyfrU6c" https://co
nsole.helium.com/api/v1/devices
Internal Server Error

**Comment by vicmgs** [comment]
The header should be called "key"

curl -G -H "key:RbTpB/Lv6R7vlKwRDOjGEM/SNLqvHdSuynnAcyfrU6c" https://co
nsole.helium.com/api/v1/devices

**Comment by weirongbo** [comment]
use my key ,it is still error








At 2021-07-16 00:44:22, "Victor Mu" ***@***.***> wrote:

The header should be called "key"

curl -G -H "key:RbTpB/Lv6R7vlKwRDOjGEM/SNLqvHdSuynnAcyfrU6c" https://co
nsole.helium.com/api/v1/devices

**Comment by weirongbo** [comment]
$ curl -G -H "key:GnbkbXKFlMbVhDJwm7bp5d4iz6QS3vC8B/81hWMvQxI" https://console.
helium.com/api/v1/devices
{"message":"invalid_api_key"}

Now the KEY is a new KEY I just created in my configuration file today, report this error
