### ISSUE TITLE
 invalid payload types

### ISSUE THREAD

**Issue by winstonzllc** [helium/console#696]
1. Are you using Helium hosted Console or running your own open source Console?
Hosted
2. If you are on Helium hosted Console, which url are you currently on? 
Staging.helium.wrt
3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47
![FEDD683B-0639-489E-8CDD-116B4AAA27A1](https://user-images.githubusercontent.com/25247430/125808147-5760e427-fb4f-491a-af49-2c5e7ef3d69c.png)
e2-8eda-e087fc03a753).
Winz I’d 4c2f11f1-74cd-4399-a7ee-655beb97b97a
Please describe your issue:
A way in console of stopping the second packet containing Battery & Temperature being sent by the Adeunis, to block the invalid payload types
![2D64E5E3-F14F-4388-9175-9F1C73891655](https://user-images.githubusercontent.com/25247430/125808314-40d5d800-be48-4e5d-8ba7-f75ed4a7dec9.png)

**Comment by vicmgs** [comment]
I'm not sure what you are asking for here. Why is invalid about the payload in your screenshot, and what are you recommending is the mechanism for blocking invalid payloads?

**Comment by winstonzllc** [comment]
Adeunis it sends the battery as a payload with no latitude and longitude so only 50% of the uplinks are successful to mappers. Can this be fixed the uplink be 100% ?

**Comment by illperipherals** [comment]
![image](https://user-images.githubusercontent.com/17368055/126392669-9dd8bf93-c918-4d9d-a7b4-0934700136fa.png)

**Comment by kent-williams** [comment]
Hi @winstonzllc,

This is a device firmware specific issue and unrelated to Console. There is no option that I am aware of to modify this on the device.

**Comment by winstonzllc** [comment]
Ok thank you for your assistance.


Sent from the all new AOL app for iOS


On Tuesday, July 20, 2021, 4:57 PM, Kent Williams ***@***.***> wrote:




Hi @winstonzllc,

This is a device firmware specific issue and unrelated to Console. There is no option that I am aware of to modify this on the device.
