### ISSUE TITLE
{"message":"invalid_api_key"}

### ISSUE THREAD

**Issue by weirongbo** [helium/console#702]
$ curl -G -H "key:GnbkbXKFlMbVhDJwm7bp5d4iz6QS3vC8B/81hWMvQxI" https://console.
helium.com/api/v1/devices
{"message":"invalid_api_key"}

Now the KEY is a new KEY I just created in my configuration file today, report this error

**Comment by ambuznego** [comment]
Can you clarify what you mean by "created in my configuration file"? To create an API key, please follow the steps in Console API Keys in https://docs.helium.com/use-the-network/console/my-account. Please make sure you activate it once you create it.

**Comment by vicmgs** [comment]
I just tried with my own key with 

curl -G -H "key:[my-key]" https://console.helium.com/api/v1/devices  

and it is definitely working. Maybe make sure you are not generating a key on the staging environment or something.
