### ISSUE TITLE
(staging) Missing Device name, EUI & other info  in Group

### ISSUE THREAD

**Issue by anandnat** [helium/console#704]
1. Are you using Helium hosted Console or running your own open source Console? No

2. If you are on Helium hosted Console, which url are you currently on? 

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue: Missing Device name, EUI & other informations when in click group label
label (staging)

**Comment by vicmgs** [comment]
@jdgemm what do you think

**Comment by vicmgs** [comment]
Deploying to staging now
