### ISSUE TITLE
Device 'Last Modified' date shows current date/time.

### ISSUE THREAD

**Issue by jthiller** [helium/console#707]
**1. Are you using Helium hosted Console or running your own open source Console?**
Hosted Console

**2. If you are on Helium hosted Console, which url are you currently on?** 
https://staging-console.helium.wtf/flows

**3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).**
`Joey`
`e9704026-b272-4faa-9e4d-a7ca6a067ac5`

**Please describe your issue:**
'Last Modified' date shows current time without any modifications.

Steps to repro:
1. Visit https://staging-console.helium.wtf/flows
2. Without making any changes, click on an existing device card.
3. Note that the 'Last Modified' time matches current time.

<kbd><img width="427" alt="image" src="https://user-images.githubusercontent.com/1965053/126341860-8c9480f8-8c2f-4731-87df-6bea2d33e96d.png"></kbd>

**Comment by jthiller** [comment]
Please add `Staging` label.

**Comment by ambuznego** [comment]
Thanks for reporting, @jthiller! I'll push a fix soon :)

**Comment by vicmgs** [comment]
fix on staging
