### ISSUE TITLE
When adding a decoder, select product and fill the code in automatically. (Staging)

### ISSUE THREAD

**Issue by oharkins** [helium/console#708]
Instead of clicking and going through the list of products in GitHub and selecting the one you want then copy and pasting the code, have the code populate with some dropdowns. based on manufacture and part and version. this would just speed up the onboarding process and make the console more user frendily.

**Comment by jdgemm** [comment]
Thanks for the feedback, we'll consider after Console 2.0 release.

**Comment by jdgemm** [comment]
The benefit of this list is that it's dynamic and users can continually add to it. In addition, the issue is we don't control this list and so can't be sure of the quality of the functions.
