### ISSUE TITLE
(staging) usability: deleting labels

### ISSUE THREAD

**Issue by phraktle** [helium/console#731]
1. Are you using Helium hosted Console or running your own open source Console? 
helium hosted

2. If you are on Helium hosted Console, which url are you currently on? 
https://staging-console.helium.wtf

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Decent Labs 79ace6cf-4fdb-4023-a7e7-21d12f3e1311

Please describe your issue:
Adding labels is straightforward, but deleting them is not. There should be a menu item "Labels" on the left nav where you can select and delete the label.

**Comment by jdgemm** [comment]
Thanks for submitting the request, this has been added to the backlog.

**Comment by vicmgs** [comment]
coming in next release
