### ISSUE TITLE
Staging Console | Add multiple labels at once

### ISSUE THREAD

**Issue by NTech242** [helium/console#734]
1. Are you using Helium hosted Console or running your own open source Console?
Hosted

2. If you are on Helium hosted Console, which url are you currently on? 
staging-console.helium.wtf

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Can we have the ability to add multiple labels to devices when creating new devices?

**Comment by vicmgs** [comment]
[device_import.csv](https://github.com/helium/console/files/6917974/device_import.csv)

We recommend using the device import feature, see sample file
