### ISSUE TITLE
Card border 

### ISSUE THREAD

**Issue by simonfuture2** [helium/console#739]
1. Are you using Helium hosted Console or running your own open source Console? helium staging 

2. If you are on Helium hosted Console, which url are you currently on? staging

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Please describe your issue:

Add feature: highlight selected Card, 
![staging_console_idea](https://user-images.githubusercontent.com/78990353/128011155-c76afb4f-0398-4062-a9bb-8c8b17bf2c7f.png)

**Comment by jdgemm** [comment]
Thanks for the request we'll add this to our backlog.

**Comment by vicmgs** [comment]
released

**Comment by simonfuture2** [comment]
that looks awesome. thanks for adding this feature and taking my thoughts
into consideration.
