### ISSUE TITLE
Cannot transfer devices to console from staging 

### ISSUE THREAD

**Issue by Alanhall007** [helium/console#753]
1. Are you using Helium hosted Console or running your own open source Console?
Both - trying to transfer some trackers from staging to live

2. If you are on Helium hosted Console, which url are you currently on? 

https://staging-console.helium.wtf/

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID

63984119-b2f6-4dcf-97dc-2320c5d84ce2

Please describe your issue:

I don’t seem to be able to transfer the devices to the live console - the devices just appear stuck in the pending status.  I removed from staging and then added using the same csv upload.

secondly, any packet transfer does not appear to be being credited to the hotspot despite being able to see the data transfer and related integrations working find through my hotspot.

**Comment by vicmgs** [comment]
Hi,

Please check if the pending status is still on your devices, they should take some time to go from pending to fully available.

As for the packet transfer crediting issue, we are currently looking into it.
