### ISSUE TITLE
IBM Watson IoT Integration

### ISSUE THREAD

**Issue by illperipherals** [helium/console#756]
This is a Helium Console prebuilt Integration along the same lines as our AWS Integration.
I have contact points over on the IBM side of things.

**Comment by jdgemm** [comment]
@illperipherals can you start setting up discussions with IBM team

**Comment by ahmadsayed** [comment]
I did not work with IBM IoT for long, but I think you can  integrate through MQTT directly

**Comment by jdgemm** [comment]
@illperipherals any update with IBM conversations?
