### ISSUE TITLE
API for Linking to Integrations

### ISSUE THREAD

**Issue by NotAnotherDivideByZero** [helium/console#775]
This is not an issue but a feature request. 
Is it possible to provide API capability to link groups to integrations.  
As we manage it all from a different platform it would allow everything to then be automated from there via API calls. 
I hope i have put this request in the correct place. Apologies if not.
keep up the good work !!

**Comment by jdgemm** [comment]
Closing as this is duplicated by: https://github.com/helium/console/issues/637
