### ISSUE TITLE
Broken project link in README

### ISSUE THREAD

**Issue by mfalkvidd** [helium/console#782]
The [README](https://github.com/helium/console/blob/dev/README.md) contains this:

> For a list of issues and prioritization, please go to our [Project page](https://github.com/orgs/helium/projects/15).

But that link returns 404. https://github.com/orgs/helium/projects/ shows a bunch of projects, but none for Console. My guess is that the Console project exists, but is only accessible by members of the Helium team.

**Comment by jdgemm** [comment]
This has been updated, we're not actively using github projects for Console.

**Comment by mfalkvidd** [comment]
Thanks!
