### ISSUE TITLE
Unable to delete an organization

### ISSUE THREAD

**Issue by cwinsby** [helium/console#794]
When deleting an organization, I am able to go through all the steps to do so but when I hit delete it is still there. There are no error messages and refreshing the page doesn't change anything. 
<img width="1431" alt="Screen Shot 2021-08-24 at 12 22 54 PM" src="https://user-images.githubusercontent.com/79541174/130682730-10b626b9-c1b4-47a1-8f7f-07c75785e7ec.png">
<img width="1416" alt="Screen Shot 2021-08-24 at 1 07 36 PM" src="https://user-images.githubusercontent.com/79541174/130682781-d294942b-f7a3-4dd7-b2c5-1a8d2f121214.png">
<img width="1433" alt="Screen Shot 2021-08-24 at 1 08 12 PM" src="https://user-images.githubusercontent.com/79541174/130682902-5967f6d7-b458-4ada-8039-d0e133470918.png">

**Comment by vicmgs** [comment]
making it a clubhouse
