### ISSUE TITLE
User confirmed invite with wrong e-mail

### ISSUE THREAD

**Issue by brunophygitall** [helium/console#822]
Good day!
First, thank you for the support!
Second, my boss recieved the invitation to the console  but when he confirmed he logged invwith a different account and the user became this different account. I excluded this wrong one and when I try to resend the invitation to the correct e-mail, it says "That email has already been invited to this organization" altough it doesn't show the other user deleted anymore...

**Comment by vicmgs** [comment]
Hi,

Invitations are not locked to particular emails and can be accepted with any email as long as you can access the link. What is the email you are trying to invite? If you do not wish to paste it here, please contact support@helium.com for help with this issue.
