### ISSUE TITLE
Coverage feature broken in self-hosted Console

### ISSUE THREAD

**Issue by mfalkvidd** [helium/console#852]
1. Are you using Helium hosted Console or running your own open source Console?
My own

2. If you are on Helium hosted Console, which url are you currently on? 
https://my-console/coverage

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Not applicable

Please describe your issue:
Using a59b2532c1064cd0b97effa9092647419511c00a

The coverage feature does not view any information regarding _Hotspot Name_, _Alias_ or _Location_. See screen shot below:
![image](https://user-images.githubusercontent.com/893502/133994669-79c8b152-041b-486a-a4a9-e1f316707ffa.png)

Same applies to the _My Hotspots_ tab.

The _Hotspot Search_ feature always returns empty result.

**Comment by ambuznego** [comment]
@mfalkvidd The job for syncing the hotspots from the API happens every hour. It's possible at the time of your screenshot, the `hotspots` table had not yet synced. Can you check again and see if it is still not showing the hotspot info?

**Comment by mfalkvidd** [comment]
Yes, the screen shot was taken shortly after I upgraded. I don’t have access to a computer now but I’ll check tomorrow and report back.

**Comment by mfalkvidd** [comment]
Coverage looks good now. Thanks!
