### ISSUE TITLE
DC integration with console API

### ISSUE THREAD

**Issue by jeanmouawad** [helium/console#887]
Integration to check DC consumption is too important with API
Also To Buy DC through API is essential Too

**Comment by jdgemm** [comment]
when you say buy DC via API, I'm assuming you mean purchase DCs via credit card correct?

**Comment by jdgemm** [comment]
Also to check DC balance, already available: `api/v1/organization`

**Comment by jeanmouawad** [comment]
> when you say buy DC via API, I'm assuming you mean purchase DCs via credit card correct?

Not necessary. Maybe burn HNT Into DC.

**Comment by jeanmouawad** [comment]
> Also to check DC balance, already available: `api/v1/organization`

It is not listed in docs. I will try api/v1/organization. Thank you

**Comment by jdgemm** [comment]
> > Also to check DC balance, already available: `api/v1/organization`
> 
> It is not listed in docs. I will try api/v1/organization. Thank you

Yes, we'll make sure that we update the docs...

**Comment by jdgemm** [comment]
Documented, here: https://docs.helium.com/api/console/#data-credit-balance

Will close for now, for cc purchase can use autopay, and burn hnt via API seems suboptimal, but if there's a lot of requests we can revisit.

**Comment by jeanmouawad** [comment]
Thank You !!!
