### ISSUE TITLE
Add support for Helium to work together with TTI Packet Broker

### ISSUE THREAD

**Issue by baranisrc** [helium/console#891]
Hello, would it be possible for Helium to work together with TTI to help LoRaWAN prosper by sharing packet routing?  TTI just created the Packet Broker [https://www.thethingsindustries.com/news/improve-your-lorawan-coverage-and-network-performance-with-packet-broker/](url) to exchange traffic with other LoRaWAN networks that use the open Internet of Things packet broker.
Thanks in advance for your consideration.

**Comment by jdgemm** [comment]
Thanks for the request and we're definitely open to the conversation with them. We have been offering roaming since the end of last year with LoRaWAN partners, https://www.helium.com/roam
