### ISSUE TITLE
Adding user-friendly help resources

### ISSUE THREAD

**Issue by jdgemm** [helium/console#909]
With more new users coming aboard, and based on product analytics data, need to provide access to more help resources (docs, videos, other resources).

General Help: Add help icon accessed anytime that provides links to help resources. This help icon accessed regardless of user location on Console.

Content, links, and icons request: https://docs.google.com/document/d/12EE3MHAlzXILZi8B8H-2s_4WEWw6Wf_hfTbZeiSiU2M/edit?usp=sharing

![](https://media.app.shortcut.com/api/attachments/files/clubhouse-assets/5bc9f50f-88ba-4c6c-b9fb-e4162bd72ce4/616ed354-142a-4330-9536-1270ea2837b0/Frame%202.png)

**Comment by PeterMain** [comment]
Sorry, wasn't sure if you'd seen the Shortcut replies, but ii'll post here. 

Existing Home is staying but is being style-tweaked. Notice update to top bar also.
<img width="1680" alt="Frame 1" src="https://user-images.githubusercontent.com/3613880/139654109-947db2d1-34cb-4630-ad49-4f65cbf4bd6f.png">

Help bar can be invoked from any page. Contains both general help topics and contextual page topic columns.
<img width="1680" alt="Frame 1" src="https://user-images.githubusercontent.com/3613880/139654200-573ffa0d-881a-4918-9418-3e7545758ce5.png">
