### ISSUE TITLE
Add uplink details from router to custom decoder functions

### ISSUE THREAD

**Issue by dpezely** [helium/console#918]
[Router](https://github.com/helium/router) added a feature recently for supplying uplink details as an optional third parameter when evaluating custom decoder functions.  This feature has marinated in staging since last week and should be in production with an imminent release.

Let's have console's UI for custom decoder functions reveal this feature to users.

From the draft text for wider communication of this new feature:

> Router integrations (called `channels` within its source code) adds the ability for custom JavaScript to retrieve uplink information in addition to the familiar data frames.

> This required adding an explicit distinction between uplink information versus frames using a new `type` field within an existing map (or object within JavaScript).

> This object gets supplied as a new third argument to custom JavaScript decoder functions.  Existing code will be unaffected, as the JavaScript spec and V8 engine allows for more parameters being passed to a JavaScript function than those named within its parameter list.  This is now an optional argument and currently only necessary for those JavaScript functions interested in this new uplink information.

Example JS code from one of router's internal tests:

```javascript
function Decoder(bytes, port, uplink_info) { 
  var decoded = {};
  if (uplink_info) {
    decoded.dev_eui = uplink_info.dev_eui;
    decoded.app_eui = uplink_info.app_eui;
    decoded.fcnt = uplink_info.fcnt;
    decoded.reported_at = uplink_info.reported_at;
    decoded.devaddr = uplink_info.devaddr;
  }
  return decoded;
}
```
The full set of keys currently:

```javascript
{
  type: "join",
  uuid: <UUIDv4>,
  id: <router device id>,
  name: <router device name>,
  dev_eui: <dev eui>,
  app_eui: <app_eui>,
  metadata: {...},
  fcnt: <integer>,
  reported_at: <timestamp>,
  port: <integer>,
  devaddr: <devaddr>,
  hotspots: {...}
}
```

**Comment by dpezely** [comment]
When [router PR#494](https://github.com/helium/router/pull/494) gets merged, you can add `"hold_time"` to the set of keys available to each custom JavaScript decoder function's new third param.

**Comment by vicmgs** [comment]
@dpezely hold_time is an integer?

**Comment by dpezely** [comment]
@vicmgs Yes, `hold_time` is a non-negative integer.

**Comment by vicmgs** [comment]
currently released to dev for testing

**Comment by vicmgs** [comment]
releasing today
