### ISSUE TITLE
Issue with the "Event log" display: 0 hotspot and no Fcnt

### ISSUE THREAD

**Issue by Oliv4945** [helium/console#921]
1. Are you using Helium hosted Console or running your own open source Console?

Helium hosted console

2. If you are on Helium hosted Console, which url are you currently on? 

https://console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).

Device ID: `e3911fc2-ad20-4c63-ac20-a78dc5648d6b`

Please describe your issue:

A message is correctly received by Helium NS and my AS. The "debug" pane is showing is as expected:
![image](https://user-images.githubusercontent.com/6248122/140783027-ae32f35f-4d79-4f8e-83b2-60f806ff403c.png)

Nevertheless the event log array does not properly displays it
![image](https://user-images.githubusercontent.com/6248122/140783465-47324c68-0dcd-40fd-9ffd-0484ad2b3dfe.png)

**Comment by vicmgs** [comment]
Hi, I am unable to find your device ID in the db of console.helium.com

Have you deleted this device?

**Comment by Oliv4945** [comment]
Hi,

Maybe... I might have recreated it because of other issues with `gateway-rs`, sorry.
You can use deviceID `69248e5c-34f8-41a7-b00f-826c6dcd3d24`

![image](https://user-images.githubusercontent.com/6248122/140897583-4b299bc7-6682-46bd-9152-d3188ed3a610.png)

**Comment by vicmgs** [comment]
Thank you, this is caused by a known issue related to dropping certain packets under high load. This issue does not affect the underlying device packet transfer to integrations, only the display of packets in the event log. We should have a fix in the next 2 weeks.

**Comment by vicmgs** [comment]
A fix on an upstream system should have improved the situation. Please reopen if needed.
