### ISSUE TITLE
Enhancement - validate user registration

### ISSUE THREAD

**Issue by disk91** [helium/console#922]
Currently to register in a router you just need to enter your email and you're in. 

When creating a private router, you don't want unknown user to register your router and create devices into the private instance. 

I would like to have some registration mechanism to limit this with some possible customization:
- at first the ability to manually add new user and deactivate the self-registration process.
- next the ability to manually validate accounts self-created

I'm also looking for the ability to limit the registration to certain domain name but this is already managed by magic-link authentication service.

**Comment by vicmgs** [comment]
We can provide the registration gate we are using in the next release.

Users will still be able to register by themselves but cannot create any orgs or devices until the admin manually approves them in the db. Due to how Magic Link works, we cannot completely deactivate the self-registration process.

**Comment by disk91** [comment]
That sounds good. There is no emergency for this need so if part of next release this is perfect.
I'm just a bit afraid about the self registering aspect you keep at the end as in term of security once the attacker is inside the system he has made 80% of the work. Magic link allows to filter on email, this can be a starting point to secure this.

**Comment by vicmgs** [comment]
releasing today with new USER_INVITE_ONLY env var
