### ISSUE TITLE
Unhide AppKey during creation of device

### ISSUE THREAD

**Issue by slavendam** [helium/console#931]
Lot of our users reported they can't get any first message in Console. After investigation, we found out reason is that they didn't see AppKey field and didn't enter AppKey.

Please UNHIDE that box during the creation of device. Any device has it's own AppKey and user must type it. So there is no reason to hide random key you generated.
When device is already added, it is ok to leave AppKey hidden.

https://github.com/helium/console/blob/9182e0c0eb87eb18b0f3f5b547cb2ede94384d45/assets/js/components/devices/DeviceNew.jsx#L250
Change to:
```
value={
     this.state.appKey
}
```

Thanks

**Comment by jdgemm** [comment]
By default upon initial add show app key.

**Comment by vicmgs** [comment]
in dev
