### ISSUE TITLE
Add horizontal scroll to Devices list

### ISSUE THREAD

**Issue by slavendam** [helium/console#932]
On smaller screens or zoomed screens it is not possible to see icons for disabling and deleting device.

Please enable horizontal scroll.

![image](https://user-images.githubusercontent.com/19354024/142728319-95862229-a6d6-4f71-a7eb-41ed6b3b6c15.png)

**Comment by vicmgs** [comment]
Hi, which OS and browser are you on? We definitely have horizontal scroll on that table enabled.

**Comment by slavendam** [comment]
Windows 10 
Google Chrome Ver 96.0.4664.45 (64-bit) - newest

**Comment by vicmgs** [comment]
added scrollbar back in for next release
