### ISSUE TITLE
Database migration error

### ISSUE THREAD

**Issue by disk91** [helium/console#934]
1. Are you using Helium hosted Console or running your own open source Console?
Own OSS Console

On every upgrade of my console, the db migration scripts retry to execute the old scripts. these scripts does not verify the state and the console crash.

```
helium_postgres | 2021-11-27 22:31:27.702 UTC [35] ERROR:  column "default_app_eui" of relation "organizations" already exists
helium_postgres | 2021-11-27 22:31:27.702 UTC [35] STATEMENT:  ALTER TABLE "organizations" ADD COLUMN "default_app_eui" varchar(255)
helium_console | ** (Postgrex.Error) ERROR 42701 (duplicate_column) column "default_app_eui" of relation "organizations" already exists
helium_console |     (ecto_sql) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
helium_console |     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
helium_console |     (ecto_sql) lib/ecto/adapters/sql.ex:686: Ecto.Adapters.SQL.execute_ddl/4
helium_console |     (ecto_sql) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
helium_console |     (ecto_sql) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
helium_console |     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
helium_console |     (ecto_sql) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
helium_console |     _build/prod/rel/console/lib/console-0.0.1/priv/repo/migrations/20210506220027_add_app_eui_to_org.exs:12: Console.Repo.Migrations.AddAppEuiToOrg.up/0
```

Is that possible to
- indicate me how to indicate the databse migration has reached the top level to avoid previous scripts to pass
- make scripts that can be rerun multiple times.

**Comment by vicmgs** [comment]
To prevent this particular script from running, just comment out the code in the "up" and "down" functions. You can't indicate migrations have reached the top level, but you can comment out old migrations to prevent them from running.

Once run successfully once, scripts cannot be rerun unless you rollback.
https://hexdocs.pm/ecto/2.2.10/Mix.Tasks.Ecto.Rollback.html
