### ISSUE TITLE
BAD Request when adding a new device with console API

### ISSUE THREAD

**Issue by disk91** [helium/console#941]
1. Are you using Helium hosted Console or running your own open source Console?
Helium console

Please describe your issue:

When creating a new device, the API always return BAD REQUEST (400)
According to documentation this should be working
```
### create device
POST https://console.helium.com/api/v1/devices
KEY: myAPIKey

{
   "name": "test2",
   "app_eui": "60...",
   "dev_eui": "60...",
   "app_key": "B8..."
}

```
I also tried to add extra fields we have when doing GET like organization_id, adr_ammowed, cf_list_enabled ... no success at all.

**Comment by vicmgs** [comment]
Add header of Content-Type: application/json to your POST requests. I can request that snippet be added to the docs.

GET requests should absolutely be working, I just tested on our docker deployed app.

**Comment by disk91** [comment]
Just easy ... My bad !
thank you
