### ISSUE TITLE
API validation email uses wrong domain in activation link

### ISSUE THREAD

**Issue by disk91** [helium/console#946]
1. Are you using Helium hosted Console or running your own open source Console?
OSS

When getting the API key validation link, the link contains the following domain name
```
https://*.helium-iot.eu/api_keys/accept/-T19Te36LBFL6T0kRwDb...
```
This domain names looks like the ENV var `SOCKET_CHECK_ORIGIN=https://*.helium-iot.eu` But this env var does not correspond to a domain name due to joker ability. Why not using `ENV_DOMAIN=console.helium-iot.eu` ? but the best would be to replace `ConsoleWeb.Endpoint` by a ENV var and use that one. Replacing this entry would allow to not touche release.exs on every console update.

**Comment by vicmgs** [comment]
How would replacing ConsoleWeb.Endpoint help?

**Comment by disk91** [comment]
ConsoleWeb.Endpoint is the console endpoint so it sounds to be the right domain name to generate a valid link
SOCKET_CHECK_ORIGIN can contains joker and is not valid for this.

**Comment by vicmgs** [comment]
ConsoleWeb.Endpoint is a file... I can definitely use ENV_DOMAIN though

**Comment by disk91** [comment]
I don't think we are talking about the samething:
I mention the release.exs file with following content:
```
config :console, ConsoleWeb.Endpoint,
  server: true,
  url: [scheme: "https", host: "console.helium-iot.eu", port: 443],
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [:inet6, port: 4000],
  secret_key_base: secret_key_base
```

where url contains scheme + domain

**Comment by vicmgs** [comment]
I can swap SOCKET_CHECK_ORIGIN for ENV_DOMAIN for email link. 

The endpoint url in releases.exs is set to 'localhost' by default since we are deploying everything on the same box with nginx forwarding. I am hesitant to change it out for your custom use of releases.exs

**Comment by disk91** [comment]
ENV_DOMAIN is the best option, but we should also have the SCHEME somewhere as it can be http or https and END domain is just the domain.

**Comment by vicmgs** [comment]
releasing ENV_DOMAIN fix today

**Comment by vicmgs** [comment]
released today
