### ISSUE TITLE
Adding my LPS8 to the Console

### ISSUE THREAD

**Issue by Kloezle** [helium/console#953]
Hello, i watched your Tutorial on Youtube about the LPS8. 
It helped me very well with the installation of the Hotspot.

But now i am in the staging-console of Helium and tried to add the device now.
I am not sure how i can connect my Hotspot now with the console, because i cant see it in the video and in the documentation there is only written that u should be carefull when u put the EUI, and the KEY into the software, but where do i need to copy them and how can i connect the console now with my device?

Can anyone please help me .
![Unbenannt](https://user-images.githubusercontent.com/95707777/145075199-8e4528fa-8ac8-47d0-bfd3-752f198f0f5d.PNG)
_.

**Comment by vicmgs** [comment]
Hi, you do not need to do anything on Console to add your hotspot to the network. Just follow the provided instructions and assert your location on the mobile app and you are all set. 

Console is meant for devices that want to send data on the network.

**Comment by Kloezle** [comment]
Hello again,

I got a Dragino LPS8 Light Hotspot that sends Data on the Network.
I followed the instructions and updated the firmware and everything like in the Video.

But i cant see how i can connect it to the Console or in generall to the Network

**Comment by PharkMillups** [comment]
Hi @Kloezle. Thanks for joining the network! The best place to get support for this will be the #gateway-development on Discord. You can join here if haven't already: https://discord.gg/mcVawqwq

I'm going to close this issue for now.
