### ISSUE TITLE
Joining problems

### ISSUE THREAD

**Issue by slavendam** [helium/console#974]
4 users from US today reported issues with Joining to network in last few days.
One user sent this:

> "Tried over 20 times with a known hotspot right next to me… Removed from the Helium console and re-added it again like yesterday and it worked the first time after that.
> Same keys"

They don't see any records in Console.

Can this be Console issue after release of v2.1.8? Maybe to related with Router?

**Comment by jdgemm** [comment]
Duplicated router issue #558
