### ISSUE TITLE
Incorrect DC Spent / Packet Transferred in multiple places

### ISSUE THREAD

**Issue by Jonzky** [helium/console#978]
1. Are you using Helium hosted Console or running your own open source Console?
Hosted Helium

2. If you are on Helium hosted Console, which url are you currently on? 
https://console.helium.com

3. If you are experiencing bugs in Helium hosted Console, please specify your Organization name and Device ID (ex. 3483050b-284d-47e2-8eda-e087fc03a753).
Device ID: f0f10f0b-a407-4f27-a40d-96a585b10b9a
Org: Jonzkys

Please describe your issue:
It looks like I'm being shown inconsistent / incorrect usages in at least two places that I can see. Both on the devices page, and then on the specific device's page.

As far as I know I've done nothing abnormal/extreme and only setup the account this week and added a Glamos flow.

![image](https://user-images.githubusercontent.com/1550144/147152544-be507839-c7a8-4ab7-b4de-4ed6489f2319.png)

![image](https://user-images.githubusercontent.com/1550144/147152660-34ee90c4-449e-46b9-94da-c20fbddfd60a.png)

I assume 2704 is the correct value.

The only thing notable I can imagine is I enabled multiple packets (all).

**Comment by vicmgs** [comment]
@Jonzky this is indeed very weird. Can I potentially reset your device metrics to keep an eye on them for the next few days?

**Comment by Jonzky** [comment]
@vicmgs Yeh, feel free to to do. 

I don't use it too often, but if you ping me once it's reset I'll send some through over the next few day.

**Comment by vicmgs** [comment]
@Jonzky much appreciated, I just reset that device

**Comment by Jonzky** [comment]
@vicmgs When I'm out and about tomorrow I will do much more queries that'll reach more hotspots - But just from home with a limited number it's still slightly visible.

![image](https://user-images.githubusercontent.com/1550144/147991125-cd1c64d6-6c3e-4541-9c6f-66a8cdb913ae.png)

**Comment by vicmgs** [comment]
@Jonzky this is good enough to go on for now. I will try to see if I can find the issue

**Comment by vicmgs** [comment]
@Jonzky did some analysis and finding it very puzzling that the all time total is getting out of sync with the others. I probably need to reset your device once more and try to follow your device as it goes out of sync. Do you know if it happens very early or late as the frames climb?

**Comment by Jonzky** [comment]
It seems to happen straight away - I just made two requests one join (OTAA) which used 4 packets in total. No issues with that.
![image](https://user-images.githubusercontent.com/1550144/148065187-0ab1bf4f-33c8-41a4-9c81-c866bfe5e96d.png)

The second hit many more hotspots and straight away went out of sync.
![image](https://user-images.githubusercontent.com/1550144/148065616-8474bd4b-bcaf-4961-a850-91c4fcea2042.png)

**Comment by vicmgs** [comment]
Thanks very much for your help! I have a good idea what is happening now, will be working on a fix
