### ISSUE TITLE
Received uplink by the AS not displayed in the console

### ISSUE THREAD

**Issue by Oliv4945** [helium/console#985]
Hi,

I am using [Helium hosted console](https://console.helium.com/devices/953f8b66-9f13-4df4-bbc4-881ccc4f8aa0).  
Device ID is `953f8b66-9f13-4df4-bbc4-881ccc4f8aa0`, I can disclose the organization name in private.

I created an AS thanks to the MQTT integration where I correctly receive the data. Unfortunately not all of them are displayed in the console. Example:

Capture from the AS:
![Helium-issue-received-as](https://user-images.githubusercontent.com/6248122/148264273-0e48e9ad-5fb7-4781-b78e-e4823c2eee27.png)

Capture from the console:
![Helium-issue-console](https://user-images.githubusercontent.com/6248122/148264240-607ed0a7-997e-4b36-94a4-0f2701b99001.PNG)

**Comment by ambuznego** [comment]
Thanks for reporting! I see the missing 34 frame in the database. Do you mind checking if it's still missing on your Device page? In the meantime, we're working on refactoring the event endpoint to avoid delays, so perhaps it will fix this type of glitch.

**Comment by Oliv4945** [comment]
Hi,

Thank you for the answer, the missing frame is listed today
![image](https://user-images.githubusercontent.com/6248122/148343926-73372072-6f6a-4fb2-b404-e0431b2c0f2e.png)

Shall I close the issue if you are already working on it?

**Comment by ambuznego** [comment]
I'll close it. Please feel free to reopen if this happens again.
