### ISSUE TITLE
API - Create Device 

### ISSUE THREAD

**Issue by Famosi** [helium/console#998]
I’d like to create a device using the helium console API. 

The documentation says that the POST request must contains `name`, `app_eui`, `app_key` and `dev_eui`. No problem with the `dev_eui` and `name` parameters but what about `app_eui `and `app_key`? How can I set them if I don’t know them? When creating a new device using the helium console, it automatically generates the two parameters. I expect to use the api the same way, that is crating a device and receive as response the app_eui and app_key. Probably I’m missing something but can’t figure out.

Thanks.

**Comment by vicmgs** [comment]
To unblock you for now:

- first generate a new device in Console UI and remember its app_eui
- while using the API, set all new device app_euis to the app_eui generated in the previous step 
- app_key is just a randomly generated string of length 32 in the key space of "0123456789ABCDEF"

**Comment by Famosi** [comment]
Thank you for the fast response. 

This means that for creating a device by using the API it is first needed to create a device by using the UI? 
Otherwise I can create all the devices with the same `app_eui` right?

**Comment by vicmgs** [comment]
Exactly, just make sure your dev_eui and app_keys are different

**Comment by waveform06** [comment]
So this requires you "know" the dev-eui and make up a "name".  Are the Helium generated ones all starting with 6081F9? Just like Dragino is A84041? Would there be a future way to request a 6081F9 one is created?

**Comment by vicmgs** [comment]
Console UI generated dev_euis all start with 6081F9 but you can change them. Not sure what you mean request? You can change the dev_eui to whatever you need it to be.

**Comment by jdgemm** [comment]
I'm curious about your use case. What kind of sensors don't include app_eui and app_key details from the manufacturer?

**Comment by Famosi** [comment]
@jdgemm I’m developing a sensor using the Wisblock by RakWirless. Each wisblock has it’s own `dev_eui` key but , I’d say obviously, neither `app_eui` nor `app_key`. 

What I’m doing is creating a website in which each user can add it’s own sensor by using the well known `dev_eui`. I’ll generate the other two parameters for the user so that I can create a new `device` on the helium console and automatically connect the device to the `flow` by assign to the device the correct `label`.

However (maybe) I didn’t get your question. Am I missing something? Maybe I’m the “manufacturer” in this case? 

At this point I’ve a question… could this be the correct approach? In case I want to produce and deliver several sensors, should I use my personal helium console to host all the devices? Currently I’m doing so. 

Thanks 😊

**Comment by jdgemm** [comment]
You can definitely host devices in your own organization and add users to the org for them to add their sensors.

**Comment by jdgemm** [comment]
This is a unique use case with a provided workaround. I'm closing this issue, but if we're hearing this is more common we'll re-open for consideration.
