### ISSUE TITLE
Add "Pending" status when keys are edited

### ISSUE THREAD

**Issue by slavendam** [helium/console#999]
1. Are you using Helium hosted Console or running your own open source Console?
Helium hosted Console
2. If you are on Helium hosted Console, which url are you currently on? 
https://console.helium.com

Please describe your issue:
When you edit keys of device it takes some time for new keys to propagate through network. There should be "Pending" status same as when device is added first time. And it should last until keys are propagated.

**Comment by jdgemm** [comment]
Thanks for the feedback. Sounds like a reasonable request. We'll see where we can add this to the backlog.

**Comment by ambuznego** [comment]
Done but commented out until implemented in Router so it can get tested. Thus, moving to next sprint.
